Add ability to run nodes with different tezos images/implementations
oxheadalpha/tezos-k8s pull request #262
Opened 2021-08-17 23:52 UTC by harryttd

closes #113 
closes #251

Fixes the first item in checklist #257

2021-09-01 20:21 UTC, elric1 requested changes

2021-09-01 20:21 UTC, elric1 commented on charts/tezos/templates/_containers.tpl
> +  {{- if and (hasKey $node_implementation "octez") (hasKey $node_implementation "tezedge") }}
I wonder if you might want to error out if there is more than one element to the dictionary instead? Oh, hmm, I just thought of something. I think that we've missed the baker/endorser images in here! I think that we need to be able to change those. For tezedge, you still use the NL baker/endorser.

2021-09-02 20:11 UTC, harryttd commented on charts/tezos/templates/_containers.tpl
> +{{- if eq (include "tezos.getNodeImplementation" $) "tezedge" }}
makes sense. so you can set the key to indicate the implementation desired but not the specific version of said implementation.

2021-09-14 20:43 UTC, elric1 commented on charts/tezos/templates/_containers.tpl
> +  {{- if and (hasKey $node_implementation "octez") (hasKey $node_implementation "tezedge") }}
We've discussed online with @nicolasochem changing the schema in a way that invalidates my request. I shall, therefore, resolve this thread.

2021-09-15 05:02 UTC, harryttd commented
@elric1 ready for your review

2021-09-15 11:21 UTC, elric1 approved these changes
Looks good to me, I like the schema and I've taken a look at the code changes. I've also started a basic setup on minikube with:
```
nodes:
  eu:
    images:
      octez: tezos/tezos:v10-release
    instances:
    - bake_using_accounts: [tezos-baking-node-0]
      config:
        shell: {history_mode: archive}
      is_bootstrap_node: true
    - is_bootstrap_node: true
    - {}
    - {}
    - {}
    runs: [octez_node, baker, endorser, logger, metrics]
    storage_size: 15Gi
  us:
    instances:
    - {}
    - {}
    - {}
    runs: [octez_node, baker, endorser, logger, metrics]
    storage_size: 15Gi
  af:
    instances:
    - {}
    - {}
    runs: [tezedge_node, baker, endorser, logger, metrics]
    storage_size: 15Gi
  tezos-node: null
```
It comes up as expected and starts baking.

2021-09-15 15:14 UTC, merged