Restore archive node filesystem archive from s3
oxheadalpha/tezos-k8s pull request #277
Opened 2021-09-15 14:21 UTC by orcutt989

Downloads an archive node filesystem snapshot that was created with [snap-to-s3](https://github.com/thenickdude/snap-to-s3) and expands it to `/var/tezos` during the `snapshot-downloader` init step of a new node.  To download and expand a 15GB snapshot takes about 5-10 minutes.

A filesystem snapshot of an EC2 volume in the form of an LZ4 level 1 compressed archive is done manually beforehand. Compression at this level adds virtually no time to decompression versus flat archive.   These snapshots live in the S3 bucket [tezos-snapshots](https://s3.console.aws.amazon.com/s3/buckets/tezos-snapshots?region=us-east-2&tab=objects#).

⚠️ This is currently using a v10 granadanet snapshot from teztnets. This URL needs to be updated to use a mainnet snapshot.

2021-09-15 18:19 UTC, nicolasochem commented
Thank you! Now that POC is working, please turn this into a feature.

Let's call the new thing a "tarball".

Create a new init container called `tarball-downloader.sh`

This init container should be conditionally injected in the pod when a `tarball_url` is given as helm value.

You can accomplish this with a new helper `shouldDownloadTarball` which will look like [`shouldDownloadSnapshot`](https://github.com/oxheadalpha/tezos-k8s/blob/master/charts/tezos/templates/_helpers.tpl#L66-L77).

Care should be taken to make sure tarball and snapshot download are mutually exclusive.

2021-09-16 19:31 UTC, nicolasochem requested changes
See inline comments: please make sure it downloads the tarball at first pod start on an empty volume, not subsequent restarts. Also, please document this new capability in `charts/tezos/values.yaml` comments.

2021-09-16 19:31 UTC, nicolasochem commented on utils/tarball-downloader.sh
> +  curl $TARBALL_URL | lz4 -d | tar -x -C /var/tezos
What happens if there is already chain data? It looks like your script will always download and unpack the tarball when the value is given. You need to check somehow. Snapshot downloader has a similar logic where it does not download the snapshot if chain data is already here.

2021-09-16 19:31 UTC, nicolasochem commented on utils/tarball-downloader.sh
> +  echo "/var/tezos does not exist."
throw an error here

2021-09-16 19:31 UTC, nicolasochem commented on charts/tezos/templates/_helpers.tpl
> +{{- if or (.Values.tarball_url)}}
why "if or"?

2021-09-16 20:13 UTC, orcutt989 commented on charts/tezos/templates/_helpers.tpl
> +{{- if or (.Values.tarball_url)}}
I'm not sure. I copied the definition from shouldDownloadSnapshit. I thought it was the same syntax.

2021-09-17 17:38 UTC, orcutt989 commented on charts/tezos/templates/_helpers.tpl
> +{{- if or (.Values.tarball_url)}}
Ah I see now nevermind.

2021-09-17 21:15 UTC, nicolasochem commented
Looks good now. Does it work? Did you try starting a granadanet node from scratch? And when you restart the pod, it does not download again?

2021-09-17 21:29 UTC, harryttd commented on utils/tarball-downloader.sh
> +	cp -v /usr/local/share/tezos/alphanet_version $node_dir
this should be removable. I don't know why it's here. it just errors

2021-09-17 21:59 UTC, orcutt989 commented on utils/tarball-downloader.sh
> +	cp -v /usr/local/share/tezos/alphanet_version $node_dir
All 4 lines or just the last 2? @nicolasochem wanted the same check in there from `snapshot-downloader.sh`

2021-09-17 22:04 UTC, orcutt989 commented
> Looks good now. Does it work? Did you try starting a granadanet node from scratch? And when you restart the pod, it does not download again?

I just tried and it does not! Wahoo! 🎉

2021-09-17 22:13 UTC, harryttd commented on utils/tarball-downloader.sh
> +	cp -v /usr/local/share/tezos/alphanet_version $node_dir
Just line 13. I select all lines usually when I my comment is on multiple 🙂

2021-09-17 22:20 UTC, nicolasochem approved these changes
thank you

2021-09-20 15:54 UTC, nicolasochem requested changes

2021-09-20 15:54 UTC, nicolasochem commented on charts/tezos/values.yaml
> +
Move this new section to line 135 where snapshots are defined.

Write
`NOTE: tarballl_url and snapshot_url are mutually exclusive. When `tarball_url` is configured, `full_snapshot_url` and `rolling_snapshot_url` must be null.`

2021-09-20 16:11 UTC, nicolasochem approved these changes
thank you!

2021-09-20 16:18 UTC, harryttd commented on charts/tezos/values.yaml
> +
This condition should be enforced in Helm

2021-09-20 16:44 UTC, harryttd commented on utils/tarball-downloader.sh
> +	cp -v /usr/local/share/tezos/alphanet_version $node_dir
I see this is marked as resolved. Was the code just not pushed yet?

2021-09-20 16:44 UTC, harryttd commented on utils/tarball-downloader.sh
> +  rm -rf $node_data_dir
please indent

2021-09-20 16:44 UTC, harryttd commented on utils/tarball-downloader.sh
> +  rm $node_data_dir/identity.json
please indent

2021-09-20 16:56 UTC, harryttd commented on charts/tezos/values.yaml
> +
Also please put this NOTE  block right after the other "alternatively" block and before the `tarball_url`. The property should not be in between 2 paragraphs both describing things about it.

2021-09-20 18:14 UTC, harryttd commented on utils/tarball-downloader.sh
> +	curl $TARBALL_URL | lz4 -d | tar -x -C /var/tezos
The tarball script will continue to execute even if a command in the pipeline fails. example of where i deliberately made the code fail and you can see the script continues:
```shell
│ Did not find pre-existing data, importing blockchain                                                        │
│   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current                             │
│                                  Dload  Upload   Total   Spent    Left  Speed                               │
│   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Error 44 : 100   219  100   2 │
│ Unrecognized header : file cannot be decoded                                                                │
│ tar: short read                                                                                             │
│ rm: can't remove '/var/tezos/node/data/identity.json': No such file or directory                            │
│ /var/tezos:                                                                                                 │
│ total 8                                                                                                     │
│ drwxrwxrwx    2 utmp     root          4096 Sep 20 18:12 client                                             │
│ drwxr-xr-x    3 utmp     root          4096 Sep 20 18:12 node
```

2021-09-20 18:31 UTC, orcutt989 commented on utils/tarball-downloader.sh
> +	curl $TARBALL_URL | lz4 -d | tar -x -C /var/tezos
i have added `set -e`

2021-09-20 18:32 UTC, orcutt989 commented on utils/tarball-downloader.sh
> +  rm $node_data_dir/identity.json
yeah for some reason my editor was forcing tabs isntead of spaces ONLY for sh files...

2021-09-20 18:33 UTC, orcutt989 commented on utils/tarball-downloader.sh
> +  rm -rf $node_data_dir
hmm weird

2021-09-20 18:34 UTC, orcutt989 commented on charts/tezos/values.yaml
> +
> This condition should be enforced in Helm

in _containers.tpl?

2021-09-20 21:06 UTC, harryttd commented on utils/tarball-downloader.sh
> +    rm $node_data_dir/identity.json
Also (based off talking via slack), if we would like some semblance of keeping track of progress, why not have `curl`, `lz4`, and `tar` all run on separate lines and have their output stored as a variable? Instead of running them as a pipeline. Then we can log things in between each command. We can also use `set -x` to log when each command is began.

2021-09-20 21:46 UTC, harryttd commented on charts/tezos/values.yaml
> +
I would probably do it in _helpers.tpl.

This is the code that checks if it should download a regular snapshot:

https://github.com/oxheadalpha/tezos-k8s/blob/master/charts/tezos/templates/_helpers.tpl#L66-L77
```yaml
{{/*
  Checks if a snapshot should be downloaded. Either full_snapshot_url or
  rolling_snapshot_url must not be null.
  Returns a string "true" or empty string which is falsey.
*/}}
{{- define "tezos.shouldDownloadSnapshot" -}}
{{- if or (.Values.full_snapshot_url)  (.Values.rolling_snapshot_url) }}
  {{- "true" }}
{{- else }}
  {{- "" }}
{{- end }}
{{- end }}
```

I would validate that if tarball is also set after checking the snapshot urls are set, then fail. Then the same logic could be done for if the tarball should be downloaded. So checking if tarball exists, if yes and also snapshot urls, then fail.
It may be possible/preferable to do this assertion as its own standalone check instead of in both the snapshot and tarball logic.

2021-09-30 18:55 UTC, orcutt989 commented on utils/tarball-downloader.sh
> +    rm $node_data_dir/identity.json
I'm implementing the better pipe command the better rm. Although breaking up the commands is a good idea, its going to involve us preempting a file name for the downloaded archive, and then the removal of the temporary file. Since we can't get useful logging out of this anyways, I am going to keep the pipe for now to avoid having to manage big temporary files. Thanks for the suggestion. 👍

2021-09-30 21:44 UTC, nicolasochem approved these changes
Thank you! I fixed conflicts, and tried to set tarball and snapshot at the same time. It failed as expected.

I tried to sync a node from a granadanet snapshot,  there was an issue because you added `set -e` and there was an alphanet_version file that does not exist anymore. I removed this line so we can keep set -e.

2021-09-30 21:46 UTC, merged