Ability to specify both archive and rolling tar urls
oxheadalpha/tezos-k8s pull request #322
Opened 2021-11-18 20:55 UTC by harryttd

PR merges the snapshot and tarball downloader scripts into a single snapshot-downloader.sh script. ("snapshot" referring to both a tezos exported snapshot and also a tar being an fs snapshot)

We allow the specification of archive and rolling tar urls as opposed to a single tar url. Helm logic checks that only either rolling tar or snap is specified. Both are not allowed.

2021-11-22 15:18 UTC, elric1 commented
Having a look, I think that it might be better to merge snapshot-{downloader,importer}. The tezos image includes wget rather than curl, but they should be functionally equivalent. Question is: can we speed things up by parallelising the download and import as we do for tarballs? If that is possible, then we should definitely do it as it would speed things up.

2021-11-22 15:58 UTC, harryttd commented
Good point that we can use wget. However I didn't really want to write regex to parse the node's history mode because Octez doesn't have jq. This PR was the easiest way for me to get the desired results as we need it for Oxheadinfra. The download + import flow is already not ideal. This PR makes it a little more ideal by having the different file types download flow all in one script.

Regarding our discussion via Slack, that is a great point to ask NL to implement snapshot import via a URL. I can make an issue on Gitlab.

2021-11-22 16:02 UTC, elric1 commented
I'm not sure how difficult it would be for them to implement, i.e. I'm not sure if the `fseek(2)` during the snapshot import. But, my guess is that it is a purely linear process of adding blocks and validating the signatures, in which it should be relatively straight--foward.

2021-11-22 16:05 UTC, elric1 commented on charts/tezos/templates/configs.yaml
> +  ARCHIVE_TARBALL_URL: "{{ .Values.archive_tarball_url }}"
I wonder if a slightly better schema might be interesting at some point, something like:
```
snapshot:
  type: tarball
  full_url: ...
  rolling_url: ...
```

2021-11-22 16:08 UTC, elric1 commented on utils/snapshot-downloader.sh
> +  rolling)  snapshot_url="$ROLLING_SNAPSHOT_URL"
I'd like to see this case as:
```
   rolling*) ...
```
as you can specify the number of cycles to store by specifying something like `rolling:2`.

2021-11-22 16:18 UTC, harryttd commented on utils/snapshot-downloader.sh
> +  rolling)  snapshot_url="$ROLLING_SNAPSHOT_URL"
our conclusion over slack is to make a new issue

2021-11-22 16:59 UTC, elric1 commented on charts/tezos/templates/configs.yaml
> +  ARCHIVE_TARBALL_URL: "{{ .Values.archive_tarball_url }}"
I created issue #325 , we can discuss it later.

2021-11-22 17:01 UTC, elric1 requested changes

2021-11-22 17:01 UTC, elric1 commented on charts/tezos/templates/nodes.yaml
> +      {{- if has "baker" $.node_vals.runs }}
Is this part of this commit or did it sneak in somehow?

2021-11-22 17:48 UTC, harryttd commented on charts/tezos/templates/nodes.yaml
> +      {{- if has "baker" $.node_vals.runs }}
I nested `baking_node` and labels under the `if`s so you can see the conditional structure more easily instead of it all being stacked on top of eachother

2021-11-23 08:36 UTC, elric1 commented on charts/tezos/templates/nodes.yaml
> +      {{- if has "baker" $.node_vals.runs }}
Ah, sorry, I didn't notice that it was whitespace only.

2021-11-23 08:36 UTC, elric1 approved these changes

2021-11-23 14:50 UTC, elric1 commented
I opened [#2138: tezos-node snapshot import should be able to take a remote URL](https://gitlab.com/tezos/tezos/-/issues/2138).

2021-11-23 15:52 UTC, orcutt989 approved these changes
Awesome thanks!

2021-11-26 18:09 UTC, merged