Chart test
oxheadalpha/tezos-k8s pull request #326
Opened 2021-11-22 21:46 UTC by elric1

From the commit:

Add a chart test framework.

Essentially, the idea is that we have a directory which contains a set of values files: test/charts/*.in.  Corresponding to each chart is the fully expanded chart that they generate.  This is stored in the same directory with the .in replaced with a .expect.  They are both checked into git.

We then provide a script called test-charts which uses "helm template" to expand our charts using each values file and makes sure that it matches the expected chart.  The script will error out if there are any differences.  It will also emit the diffs.

If the diffs are acceptable, just:
```
            :; ./bin/test-charts -r <values_file_name>
```
will put the new expected chart output in place where you can add it to your commit.

We also found a YAML diff program called dyff and add it as an option to helm-compare-versions, we fix a drive-by. And we instrument helm-compare-versions to try to use the test values files if you specify one.

2021-12-03 18:22 UTC, nicolasochem requested changes
This is great, please add a github action to run the test for every PR and push. Thank you.

2021-12-03 18:22 UTC, nicolasochem commented on test/charts/mainnet.in
> +      octez: tezos/tezos:v10-release
maybe leave this blank? so we don't have to maintain this file.
Actually, can mainnet.in be empty? Launching the chart with no values at all should work and spin up a mainnet node.

2021-12-03 18:22 UTC, nicolasochem commented on test/charts/mainnet.in
> +open_acls: true
this value is outdated.

2021-12-03 18:22 UTC, nicolasochem commented on test/charts/private-chain.in
> +  tezos: 'tezos/tezos:v10-release'
should be octez

2021-12-03 21:44 UTC, elric1 commented on test/charts/private-chain.in
> +  tezos: 'tezos/tezos:v10-release'
Yes it should! I've fixed it. I decided to have both a mainnet which is empty as you suggested and a mainnet2 which has three nodes in it. I also made the images different at the global and statefulset level in private-chain to make sure that that is being tested.

2021-12-04 00:32 UTC, nicolasochem approved these changes

2021-12-04 02:20 UTC, merged