Rename tezos node
oxheadalpha/tezos-k8s pull request #353
Opened 2022-01-07 02:56 UTC by harryttd

closes #352

2022-01-07 03:00 UTC, harryttd commented on README.md
> -
I got rid of creating a full node and just left the user with creating the default rolling node. We would need to introduce needing a values.yaml here and referencing it, and I think it is not necessary at this point. We can't just `--set tezos-node....` anymore, bec the node names are not uniform. They reflect their history modes.

2022-01-07 21:39 UTC, nicolasochem requested changes
Looks good except some of your readme changes. I don't like `full-baking-node`, it sounds awkward. Plus the recommendation is to use rolling nodes for baking. Can you just name it `baking-node` and set it as rolling in the config example?

Also `full-tezedge-node` should be named `tezedge-full-node` I think.

2022-01-11 02:37 UTC, nicolasochem approved these changes
thanks!

2022-01-11 02:38 UTC, harryttd commented
Thank you Sir

2022-01-11 02:39 UTC, merged