add the accuser
oxheadalpha/tezos-k8s pull request #360
Opened 2022-01-31 13:54 UTC by elric1

2022-02-01 19:25 UTC, harryttd commented
Please add accuser to the values.yaml comments: https://github.com/oxheadalpha/tezos-k8s/blob/master/charts/tezos/values.yaml#L85-L86

2022-02-01 19:26 UTC, harryttd requested changes
Please add accuser to the values.yaml comments:
https://github.com/oxheadalpha/tezos-k8s/blob/master/charts/tezos/values.yaml#L85-L86

2022-02-01 19:36 UTC, harryttd commented on charts/tezos/templates/_containers.tpl
> +    - /usr/local/bin/tezos-accuser-{{ .command }}
Do we need to provide a path to the client directory? 

Maybe the baker-endorser.sh script can be utilized if all of its internal code can and should be used for accuser.

2022-02-02 08:39 UTC, elric1 commented on charts/tezos/templates/_containers.tpl
> +    - /usr/local/bin/tezos-accuser-{{ .command }}
Hmmm, ISTR that I have some code around somewhere that refactors all of this. I wonder what I did with it, but it would have done this.
But to the point at hand: we could put those directories in place and it would be nice for symmetry (and I will during the refactor code which is lying around somewhere), however, interestingly, the accuser doesn't need any of it. It's config is separate, it only speaks HTTP to localhost and it doesn't require access to any accounts. In essence, the accuser just generates an anymous accusation and the proceeds of any penalties accrues to the first baker to include said accusation in the block that they are baking.

2022-02-08 22:53 UTC, nicolasochem approved these changes
I tried it on my minikube and it works. Thank you

2022-02-08 23:12 UTC, merged