Snapshot Engine
oxheadalpha/tezos-k8s pull request #364
Opened 2022-02-10 19:40 UTC by orcutt989

Adds Snapshot Engine Helm chart and Docker image.

2022-02-10 21:51 UTC, nicolasochem reviewed
Thank you for this, a few initial comments.

2022-02-10 21:51 UTC, nicolasochem commented on snapshot_maker/volumeFromSnap.yaml
> +  namespace: mainnet-shots-2
This should not be hardcoded.

2022-02-10 21:51 UTC, nicolasochem commented on snapshot_maker/mainJob.yaml
> +  namespace: mainnet-shots
This should not be hardcoded.

2022-02-10 21:51 UTC, nicolasochem commented on snapshot_maker/snapshot-website-base/_config.yml
> +            - item_name: Granadanet
should be hangzhou and ithaca here? I think this is what creates the links on the top right.

2022-02-10 21:51 UTC, nicolasochem commented on snapshot_maker/snapshotMakerJob.yaml
> +          image: 082993323195.dkr.ecr.us-east-2.amazonaws.com/snapshot-maker:latest
should not be hardcoded

2022-02-10 21:51 UTC, nicolasochem commented on snapshot_maker/mainJob.yaml
> +              #!/bin/sh
can we put that in a separate file and use Roland's method?

2022-02-10 23:14 UTC, harryttd commented
Please rename the PR to reflect what it is actually accomplishing

2022-02-11 06:02 UTC, harryttd requested changes
This is awesome work!

I'm not done reviewing yet. I've mostly made templating comments.

I still need to go through the snapshot_maker code and understand it better. I'd also like to see if we can perhaps make some values more templatizeable. Bec many values are defined as templatizeable or hardcoded in one chart, but then they are expected to be static in other charts / templates, as they are hardcoded.

2022-02-11 20:40 UTC, harryttd commented on charts/snapshot-warmer/README.md
> +All of these resources can be deployed to a real AWS EKS cluster with https://github.com/oxheadalpha/oxheadinfra. However testing in minikube without AWS mocking tools would not be possible.
I don't think we need to mention oxheadinfra in this repo. We can just say you need an EKS cluster. 
 
Also I'm thinking that we should have a full list of all the IAM roles, policies, configurations, etc that we know we need, and provide them in this readme or something. Otherwise it is very unclear how to fully deploy a working chart. 

```suggestion
This Helm Chart is configured to work only with an AWS EKS cluster. It requires AWS IAM Roles and Policies, an AWS OIDC provider, and the EKS CSI driver to perform necessary actions on AWS resources from Kubernetes Pods.

Testing in minikube without AWS mocking tools is not possible. You should create your own EKS cluster to test.
```

2022-02-14 21:23 UTC, harryttd requested changes
more comments

2022-02-15 00:44 UTC, harryttd commented on snapshot_maker/Dockerfile
> +    && wget -q -O /usr/bin/yq $(wget -q -O - https://api.github.com/repos/mikefarah/yq/releases/latest \
we might want to pin yq? He's had breaking major changes in the past

2022-02-15 00:48 UTC, harryttd commented on charts/snapshot-warmer/scripts/snapshot-warmer.sh
> +NAMESPACE="${NAMESPACE}" yq e -i '.metadata.namespace=strenv(NAMESPACE)' createVolumeSnapshot.yaml
I don't think we should need to prefix with `NAMESPACE="${NAMESPACE}"`. It is assigning a variable's value to the value it already is. It is a global env var passed in to the container via the pod specification and should be available everywhere. This comment applies to multiple places in each of the snapshotting bash scripts we have.
```suggestion
yq e -i '.metadata.namespace=strenv(NAMESPACE)' createVolumeSnapshot.yaml
```

2022-02-15 01:33 UTC, harryttd commented on charts/snapshot-warmer/scripts/snapshot-warmer.sh
> +PERSISTENT_VOLUME_CLAIM=var-volume-snapshot-"${HISTORY_MODE}"-node-0
FYI, If we were to pass the node class value the current warmer is deployed for as an env var, this works and we wouldn't have to hardcode the volume's full name:
```shell
PERSISTENT_VOLUME_CLAIM=$(kubectl get -n "$NAMESPACE" po -l node_class="$NODE_CLASS" \
-o jsonpath='{.items[0].spec.volumes[?(@.name=="var-volume")].persistentVolumeClaim.claimName}')
```

It might also be nice combined with the idea of flattening the `nodes` structure in values.yaml to add a `volumeName` field to each node class. That would be in addition to `history_mode` being the only field so far. This would templatize code even more instead of making the snapshot code hardcoded and tightly dependent upon what is currently the default value in tezos-k8s.

```yaml
nodes:
  snapshot-archive-node:
    history_mode: archive
    volumeName: var-volume
```
```shell
kubectl get -n "$NAMESPACE" po -l node_class="$NODE_CLASS"  \
-o jsonpath="{.items[0].spec.volumes[?(@.name==\"$VOLUME_NAME\"})].persistentVolumeClaim.claimName}"
```

2022-02-15 05:03 UTC, harryttd commented on charts/snapshot-warmer/scripts/snapshot-warmer.sh
> +  while [ "$(kubectl get volumesnapshots -o jsonpath='{.items[?(.status.readyToUse==true)].metadata.name}' --namespace "${NAMESPACE}" -o go-template='{{len .items}}' --selector='!history_mode')" -gt
This kubectl cmd is run 8 times in this file. It can be made into a function to shorten it a good bit. Something like:
```shell
getSnapshotNames() {
  local readyToUse="${1##readyToUse=}"
  shift
  kubectl get volumesnapshots -o jsonpath="{.items[?(.status.readyToUse==$readyToUse)].metadata.name}" \
    --namespace "$NAMESPACE" "$@"
}
getSnapshotNames readyToUse=false -o go-template='{{len .items}}' --selector='!history_mode'


```

2022-02-15 05:18 UTC, harryttd commented
Question on the kubectl commands we use in regards to the sleeping we do: Why not just use `kubectl wait` cmd? 

https://mrkaran.dev/posts/kubectl-wait/
https://kb.novaordis.com/index.php/Kubectl_wait

There is also a `--wait` flag you can pass to cmds. But it may be that the `kubectl wait` is the better way to do it. Could be because you can pass multiple resources to it.

`kubectl wait --help`

2022-02-15 05:51 UTC, harryttd commented on snapshot_maker/snapshotMakerJob.yaml
> +          image: 082993323195.dkr.ecr.us-east-2.amazonaws.com/snapshot-maker:latest
Hmmm I just realized that for our comments about hardcoding images, I think we would actually want to hardcode it to `tezos-k8s-snapshot-maker:dev`

2022-02-15 06:21 UTC, orcutt989 commented
Never seemed to work right unfortunately.

2022-02-15 06:30 UTC, harryttd commented on snapshot_maker/Dockerfile
> +FROM jekyll/jekyll:builder
I think we will have a problem with publishing the snapshot-maker container to docker hub for 2 reasons:

- I don't believe we updated our docker hub credentials in github secrets when we moved from TQ to OA. Looking at the CI logs for dockerfile publish step, I see that we are getting an unauthorized error. The CI code will pass the publish step if the curl command failed to create the docker image repo. It should really check the response from docker hub. If it gets an error, only then error, but if the repo exists we should be able to check for that in the response and then exit successfully.
<img width="400" alt="Screen Shot 2022-02-15 at 1 22 11 AM" src="https://user-images.githubusercontent.com/19419199/154004243-c69b77af-4015-441e-b493-87672aed3555.png">

Relevant code:https://github.com/oxheadalpha/tezos-k8s/blob/d8b7336d9a4de7098fe35c21c48bc75653e2721a/.github/workflows/ci.yml#L135-L140 

https://github.com/oxheadalpha/tezos-k8s/blob/d8b7336d9a4de7098fe35c21c48bc75653e2721a/.github/workflows/ci.yml#L166-L179


 
- I _think_ this will be an issue for us: The format for docker image naming is to use `-`. Not `_`. The CI will publish the snapshot-maker image as `tezos-k8s-snapshot_maker`, bec `snapshot_maker` is the name of the folder containing the dockerfile. The CI looks at folders containing dockerfiles and uses the name of the folder for the image name. I think we need to keep the format consistent and should rename the file using `-`. We can if we decide to have the CI substitute `_` for `-` and leave the inconsistency. IF we decide to change the folder name, we should likely do so after all the comments have been addressed. Changing the name before hand might mess with the github comments as the files are now in a new directory. I should have made it more explicit in DEVELOPMENT.md to use `-`: https://github.com/oxheadalpha/tezos-k8s/blob/publish-to-xtz-shots/DEVELOPMENT.md#creating-docker-images

2022-02-15 06:33 UTC, harryttd commented
>Question on the kubectl commands we use in regards to the sleeping we do: Why not just use kubectl wait cmd?
>> Never seemed to work right unfortunately.

It does seem actually to be considered an experimental command:
```shell
❯ k wait --help
Experimental: Wait for a specific condition on one or many resources.
```
Cool you tried though. Now we know :) 

>

2022-02-15 06:50 UTC, harryttd commented on snapshot_maker/snapshot-website-base/_config.yml
> +title: Tezos Snapshots
If I understand correctly how the website is created, the zip and upload job will bundle the Jekyll project and upload it to s3. The Jekyll site is bundled together with the docker image in tezos-k8s.

It is likely more ideal to create a separate repo to manage the website instead of building it inside the docker image and committing it in tezos-k8s. The site is very customized for xtz-shots and we are making xtz-shots and the website implementation a dependency of tezos-k8s. I don't think we should be managing our front end for snapshots inside tezos-k8s. I think there is a line to draw here for separation of concerns. IMO.

We can create a separate repo and then pass a url to the repo as a variable. The job can git clone it and bundle and upload the project. This way a user can optionally have a front end if they want. If they do, they can create it however they want and host it themselves wherever they choose, pointing to the tars in S3. I guess they can also pass a url to their Jekyll site and we can bundle and upload it for them. If they don't want to host a public site, they can just store their tars in S3 and download them with an S3 url.

2022-02-15 17:10 UTC, orcutt989 commented on snapshot_maker/snapshotMakerJob.yaml
> +          image: 082993323195.dkr.ecr.us-east-2.amazonaws.com/snapshot-maker:latest
this is being overridden by pulumi fyi. pulumi feeds in a value for the image at run time. I think we can make this `""` if we want.

2022-02-15 17:22 UTC, orcutt989 commented on charts/snapshot-warmer/scripts/snapshot-warmer.sh
> +NAMESPACE="${NAMESPACE}" yq e -i '.metadata.namespace=strenv(NAMESPACE)' createVolumeSnapshot.yaml
This is yq specific syntax. Check it out -

```bash
$ NAMESPACE=test
$ yq e -i '.metadata.namespace=strenv(NAMESPACE)' createVolumeSnapshot.yaml
$ cat createVolumeSnapshot.yaml
metadata:
  namespace: ""
$ NAMESPACE="${NAMESPACE}" yq e -i '.metadata.namespace=strenv(NAMESPACE)' createVolumeSnapshot.yaml
$ cat createVolumeSnapshot.yaml
metadata:
  namespace: "test"
```

2022-02-15 17:31 UTC, orcutt989 commented on snapshot_maker/Dockerfile
> +FROM jekyll/jekyll:builder
I don't know why I used underscore. I think there was a reason, but I can't remember right now.

2022-02-15 17:52 UTC, nicolasochem commented on snapshot_maker/mainJob.yaml
> +              #!/bin/sh
right, an approach would be to run helm inside the container and deploy the snapshot job using helm. but that's probably a big refactor.

2022-02-15 17:54 UTC, nicolasochem commented on snapshot_maker/snapshotMakerJob.yaml
> +          image: 082993323195.dkr.ecr.us-east-2.amazonaws.com/snapshot-maker:latest
ideally, when we do templating we should have a template file, with the sections to replace delineated with `{{}}` or equivalent.

2022-02-15 18:02 UTC, orcutt989 commented on charts/snapshot-warmer/scripts/snapshot-warmer.sh
> +  while [ "$(kubectl get volumesnapshots -o jsonpath='{.items[?(.status.readyToUse==true)].metadata.name}' --namespace "${NAMESPACE}" -o go-template='{{len .items}}' --selector='!history_mode')" -gt
This is a great suggestion. I have spent some time staring at the code and seeing multiple places where I need to do this, but it would require some refactoring.  Every time I put a loop it, in seems to move faster/more unpredictably than I can put waits in, or sleeps. Results are unpredictable so I stuck with the copy pastes for now.

2022-02-15 18:12 UTC, nicolasochem commented on snapshot_maker/snapshot-website-base/_config.yml
> +title: Tezos Snapshots
We are already doing this - it's the jekyll remote theme. 

What we can do is pass the remote theme `oxheadalpha/xtz-shots-website` as a helm variable instead of hardcoding it in the container.

The annoying thing is all the header structured data. It should not be part of _config.yml. This can probably be moved to the remote theme repository.

2022-02-15 18:41 UTC, harryttd commented on charts/snapshot-warmer/scripts/snapshot-warmer.sh
> +NAMESPACE="${NAMESPACE}" yq e -i '.metadata.namespace=strenv(NAMESPACE)' createVolumeSnapshot.yaml
I just tested it with using `export NAMESPACE` without prepending the env var to the `yq` cmd and it works. Export makes it a global var. The env vars are being passed into the container from the pod as global env vars, so this should work. Was this tested before and it didn't work?
```shell
❯  NAMESPACE=test
❯  yq e -i '.metadata.namespace=strenv(NAMESPACE)' createVolumeSnapshot.yaml
❯  cat createVolumeSnapshot.yaml | head -5
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: "2021-11-07-01-13-02-node-snapshot"
  namespace: ""
❯ export NAMESPACE=test
❯ yq e -i '.metadata.namespace=strenv(NAMESPACE)' createVolumeSnapshot.yaml
❯ cat createVolumeSnapshot.yaml | head -5
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: "2021-11-07-01-13-02-node-snapshot"
  namespace: "test"

2022-02-15 18:42 UTC, harryttd commented on snapshot_maker/Dockerfile
> +FROM jekyll/jekyll:builder
> We did update the creds this summer when we migrated tezos-k8s. I think the issue is that there isn't a repo created for snapshot_maker.

This error is occurring for releases of tezos-k8s that do not have snapshot maker yet.

2022-02-15 18:53 UTC, harryttd commented on snapshot_maker/snapshot-website-base/_config.yml
> +title: Tezos Snapshots
Oh very cool. Yes we should (optionally) be able to pass a theme in and have the project bundle it. 

We don't need to commit the .gitignore. The gem files I guess we need to be able to build the remote theme.

Do we need to be creating the index.md file in zip and upload? Can't that be moved as well?

2022-02-15 18:59 UTC, orcutt989 commented on snapshot_maker/snapshot-website-base/_config.yml
> +title: Tezos Snapshots
I think the separate repo is a great idea, but is a bit of a lift for this PR.  Right now zip and upload pulls the latest artifact info and pushes it that way we prevent any old information getting put up there. I put some time into thinking about it and that's the best thing I could come up with for the time being.  If we had a separate repo we'd need to set up remote API git commits/CI runs.

2022-02-15 19:15 UTC, nicolasochem commented on snapshot_maker/snapshot-website-base/_config.yml
> +title: Tezos Snapshots
@harryttd we can remove gitignore. Yes, the markdown file needs to be created here. It's like a metadata file, but for humans.

2022-02-15 19:41 UTC, harryttd commented on snapshot_maker/snapshot-website-base/_config.yml
> +title: Tezos Snapshots
> @harryttd we can remove gitignore. Yes, the markdown file needs to be created here. It's like a metadata file, but for humans.

From slack discussion: we should be able to add the necessary data to a config file that can be passed to Jekyll to render and not need to create the index.md file in zip&upload.

2022-04-04 17:47 UTC, orcutt989 commented on charts/snapshot-scheduler/README.md
> +If your `values.yaml` needs at least 2 Tezos nodes, 1 with **archive** history mode, and another **rolling** history mode.
Ah you fixed this with your refactor of the chart. Thanks!

2022-04-04 17:56 UTC, orcutt989 commented on charts/snapshot-scheduler/README.md
> +```
Great suggestion. I actually think I was able to simplify this further by just using the `$config.labels.node_class_history_mode` that is already being used.

2022-04-04 18:03 UTC, orcutt989 commented on charts/snapshot-scheduler/README.md
> +```
On second thought I think there may be a lot of refactoring involved in this as much of tezos-k8s relies on this structure https://github.com/oxheadalpha/tezos-k8s/search?q=%22config%22+%22history_mode%22.

2022-04-04 18:20 UTC, harryttd commented on charts/snapshot-scheduler/README.md
> +```
Why does this require a lot of refactoring? This is separate from tezos-k8s. it's its own chart

2022-04-04 18:25 UTC, orcutt989 commented on charts/snapshot-scheduler/README.md
> +```
My understanding is that tezos-k8s needs `instances[].config.shell.history_mode` for the node config as seen in the link I provided. 

If we get rid of that the tezos node wont know what history mode to start as right? We can add what you suggested, but then we're doubling up history mode information when now we are using the same information for the snapshot maker that tezos-k8s is using.

2022-04-04 18:36 UTC, harryttd commented on charts/snapshot-scheduler/README.md
> +```
It needs that struct when defining nodes in the tezos-k8s chart. The snapshot-engine chart is not defining nodes that should be created. It is targeting nodes that are created by the former chart. Hence you only need a simple flat structure.

I think your point:
> Great suggestion. I actually think I was able to simplify this further by just using the $config.labels.node_class_history_mode that is already being used.

is good and we don't need to specify the history mode in values.yaml. The warmer job (and whatever else that needs to) can `kubectl get statefulset` and check the `node_class_history_mode` to determine the history mode, and fail if the label isn't specified. So instead of https://github.com/oxheadalpha/tezos-k8s/pull/364/files#diff-0aa45a47facc9d1c918bd191fdcd2ef0f6144606426f8c3dbecabed30b9eacedR40, you would just get the label via kubectl. And no more need to also write the hist mode in values.y

2022-04-04 18:41 UTC, orcutt989 commented on charts/snapshot-scheduler/README.md
> +```
Thanks for the clarification, but I'm still not understanding something.

If I remove `instances[].config.shell.history_mode` from namespace/values.yaml then the nodes don't create.  Why would we add a duplicate set of values when we could use the ones that are already there for tezos-k8s?

IE
```
nodes:
  rolling-node: null
  snapshot-archive-node:
    >>history_mode: archive
    labels:
      node_class_history_mode: archive
    storage_size: 100Gi
    storageClassName: ebs-sc
    runs:
      - octez_node
    instances:
      - config:
          shell:
            history_mode: archive
  snapshot-rolling-node:
    >>history_mode: rolling
    labels:
      node_class_history_mode: rolling
    storage_size: 80Gi
    storageClassName: ebs-sc
    runs:
      - octez_node
      - metrics
    instances:
      - config:
          shell:
            history_mode: rolling

node_config_network:
  chain_name: hangzhounet

images:
  octez: tezos/tezos:v12.2

protocols:
  - command: 010-PtGRANAD

full_snapshot_url: null
rolling_snapshot_url: null
archive_tarball_url: https://hangzhounet.xtz-shots.io/archive-tarball
rolling_tarball_url: https://hangzhounet.xtz-shots.io/rolling-tarball
```

Snapshot-maker won't be deployed without tezos-k8s, so I am not understanding how it "doesnt need" the tezos k8s values?

2022-04-05 16:40 UTC, orcutt989 commented on charts/snapshot-scheduler/README.md
> +```
It was suggested we separate out the values files for tezos-k8s and snapshot-engine, but my concern is that this will involve refactoring all the tezos-k8s places that expects `values.yaml`.

2022-04-12 19:52 UTC, orcutt989 commented on charts/snapshot-scheduler/README.md
> +Deploy with https://github.com/oxheadalpha/oxheadinfra
Overhauled Readme. Thanks for the feedback!! 🤠

2022-04-12 21:28 UTC, harryttd requested changes
Great work on the readme! I left a few more closing comments.

Couple of things:
- Please rename the PR to something like `Snapshot Engine`
- This comment https://github.com/oxheadalpha/tezos-k8s/pull/364#discussion_r806483357 regarding publishing the engine docker image still needs to be addressed.
    - The credential issue is the first thing.
    - I think we will also need to update the github workflow file to properly name the docker images when they are published. We currently name the images `tezos-k8s<DOCKER FOLDER NAME>`. So all of our images consist of `-`.  With snapshot engine being named `snapshotEngine` I think it will end up making our image names inconsistent (`tezos-k8s-snapshotEngine` vs `tezos-k8s-snapshot-engine`. We might want to do some regex in the worflow file to always convert to `-`.

2022-04-12 21:28 UTC, harryttd commented on charts/snapshotEngine/README.md
> +docker push YOUR_ECR_URL/snapshot-maker:latest
`snapshotEngine`

2022-04-12 21:28 UTC, harryttd commented on charts/snapshotEngine/README.md
> +Subsequent jobs and pods are dependent on AWS S3 buckets, AWS ACM Certificates, Route 53 DNS Records, and AWS Route 53 domains.
I think this was from the old readme. Don't think we need all of this. Some of it is repeating what is already above and some of it seems to be warmer specific.

Also the resource creation list is a bit inaccurate. Warmer and scheduler deployments are always both created. also they will be created per node history type. So if you have rolling and archive, you will get 4 deployments.
Also a configmap is created.

2022-04-12 21:28 UTC, harryttd commented on charts/snapshotEngine/README.md
> +#### Snapshot Scheduler Deployment
`####` -> `###` ?

2022-04-12 22:20 UTC, nicolasochem commented on snapshotEngine/mainJob.yaml
> +              # Replace this with kubectl wait.  These loops wait on the RPC to come online and prevent log from printing same line
Is this a FIXME? Are we actually planning to replace this with `kubectl wait`?

2022-04-12 22:20 UTC, nicolasochem commented on snapshotEngine/mainJob.yaml
> +              # Tezos devs have advised us that it is safer to target HEAD~2 for rolling artifacts.
```suggestion
              # In tenderbake, any block at HEAD~2 is final. We are targeting HEAD~2 for rolling artifacts.
              # Otherwise, we may create a snapshot from an uncle block, which would not import succesfully.
```

2022-04-12 22:20 UTC, nicolasochem commented on snapshotEngine/zip-and-upload.sh
> +curl -o index.md https://raw.githubusercontent.com/oxheadalpha/xtz-shots-website/master/snapshot.md
We spent time separating out the website content from the snapshotter jobs, so perhaps this URL should be a helm value that we turn into an env var, instead of hardcoded?

2022-04-12 22:20 UTC, nicolasochem commented on charts/snapshotEngine/README.md
> +3. Scope this new IAM role with a Trust Policy wit the following content:
```suggestion
3. Scope this new IAM role with a Trust Policy with the following content:
```

2022-04-12 22:20 UTC, nicolasochem commented on charts/snapshotEngine/scripts/snapshot-warmer.sh
> +      # # Get EBS snapshot progress
what's with this commented out section?

2022-04-12 22:20 UTC, nicolasochem commented on charts/snapshotEngine/README.md
> +20. Build web page with Jekyll
A section about jekyll would be good? Say that the engine expects an external jekyll repo, with a specific `snapshot.md` file in it.

2022-04-12 22:20 UTC, nicolasochem commented on snapshotEngine/snapshot-website-base/_config.yml
> +remote_theme: oxheadalpha/xtz-shots-website
We are still using remote theme but we relocated `snapshot.md` to the other repo? Was this the compromise?

2022-04-13 16:16 UTC, nicolasochem commented on charts/snapshot-scheduler/values.yaml
> +  octez: tezos/tezos:v11-release
Is it possible to have the default match the default of tezos-k8s? so if I install snapshot-engine without values.yaml and the tezos chart without values.yaml, the snapshot engine will find the right image to snapshot? I think it would be `archive-node-0` in this case.

2022-04-13 20:24 UTC, nicolasochem approved these changes
Let's merge, all the remaining concerns can be addressed in subsequent PRs

Thank you! This was a huge chunk of work, as the length of the README can testify.

2022-04-13 20:25 UTC, merged

2022-04-13 20:46 UTC, harryttd commented on charts/snapshotEngine/Chart.yaml
> +apiVersion: v2
@orcutt989 The description was still missed. Please either make an issue or commit

2022-04-13 20:48 UTC, harryttd commented on charts/snapshotEngine/values.yaml
> +  snapshotEngine: tezos-k8s-snapshot-maker:dev
@orcutt989 Please see my previous comment. The image name was still not addressed and I'm not certain that the published chart will work because it will be looking for an image that doesn't exist. Please fix

2022-04-13 21:27 UTC, nicolasochem commented on charts/snapshotEngine/values.yaml
> +  snapshotEngine: tezos-k8s-snapshot-maker:dev
Looks like it worked in the published chart?

```
nochem@fedora /tmp $ wget https://github.com/oxheadalpha/tezos-helm-charts/raw/main/snapshotEngine-6.5.0.tgz
--2022-04-13 14:25:43--  https://github.com/oxheadalpha/tezos-helm-charts/raw/main/snapshotEngine-6.5.0.tgz
Resolving github.com (github.com)... 192.30.255.112
Connecting to github.com (github.com)|192.30.255.112|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/oxheadalpha/tezos-helm-charts/main/snapshotEngine-6.5.0.tgz [following]
--2022-04-13 14:25:44--  https://raw.githubusercontent.com/oxheadalpha/tezos-helm-charts/main/snapshotEngine-6.5.0.tgz
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.108.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 8448 (8.2K) [application/octet-stream]
Saving to: ‘snapshotEngine-6.5.0.tgz’

snapshotEngine-6.5.0.tgz                      100%[==============================================================================================>]   8.25K  --.-KB/s    in 0.001s  

2022-04-13 14:25:44 (16.1 MB/s) - ‘snapshotEngine-6.5.0.tgz’ saved [8448/8448]

nochem@fedora /tmp $ tar xvfz snapshotEngine-6.5.0.tgz 
snapshotEngine/Chart.yaml
snapshotEngine/values.yaml
snapshotEngine/templates/configmap.yaml
snapshotEngine/templates/rbac.yaml
snapshotEngine/templates/snapshot-scheduler.yaml
snapshotEngine/templates/snapshot-warmer.yaml
snapshotEngine/README.md
snapshotEngine/scripts/snapshot-warmer.sh
nochem@fedora /tmp $ cd snapshotEngine/
nochem@fedora /tmp/snapshotEngine $ cat values.yaml  
tezos_k8s_images:
  snapshotEngine: oxheadalpha/tezos-k8s-snapshot-engine:6.5.0
images:
  octez: tezos/tezos:v12.2
```

2022-04-13 21:27 UTC, nicolasochem commented on charts/snapshotEngine/values.yaml
> +  snapshotEngine: tezos-k8s-snapshot-maker:dev
ah, nevermind, it should be `tezos-k8s-snapshotengine:6.5.0`, this indeed needs fixing.

2022-04-13 21:29 UTC, harryttd commented on charts/snapshotEngine/values.yaml
> +  snapshotEngine: tezos-k8s-snapshot-maker:dev
JImmy did a commit directly to master after i pointed it out. I guess the release missed it?

I am making a quick PR for some other things. i will add this

2022-04-13 22:42 UTC, harryttd commented on charts/snapshotEngine/README.md
> +chainWebsiteMarkdown: url_to_md_file # Url of markdown file that will host links to your
This section needs to be updated based on comments we spoke about over slack