Add a way to define env vars in values.yaml
oxheadalpha/tezos-k8s pull request #393
Opened 2022-03-15 18:28 UTC by elric1

I am resubmitting my prior work on environment variables, but I have updated it to be able to set env vars on a container by container basis. This could be used for `TEZOS_LOG`, but also for things like `HTTP_PROXY` or `LD_PRELOAD`.

2022-03-16 09:10 UTC, elric1 commented
I think that the failed helm lint is because the version of helm that is doing the linting is quite old. It passes this test on my local box.

2022-03-17 03:38 UTC, nicolasochem reviewed
I tried `mkchain` with no parameters. It works.

Then I added this, as per the examples in values.yaml

```
 60 node_globals:                                                                                                                                                                    
 61   env:                                                                                                                                                                           
 62     baker:                                                                                                                                                                       
 63       TEZOS_LOG: "* -> debug"
```

But helm templating failed:

```
[venv] nochem@fedora ~/workspace/tezos-k8s () $ helm upgrade nico -f nico_values.yaml  charts/tezos --namespace nico
Error: UPGRADE FAILED: YAML parse error on tezos-chain/templates/nodes.yaml: error converting YAML to JSON: yaml: line 128: did not find expected alphabetic or numeric character
```

Helm template --debug gives:

```
      volumes:                                                                                                                                                                       
        - emptyDir: {}                                                                                                                                                               
          name: config-volume                                                                                                                                                        
        - emptyDir: {}                                                                                                                                                               
          name: var-volume                                                                                                                                                           
        - name: faucet-commitments                                                                                                                                                   
          emptyDir: {}                                                                                                                                                               
Error: YAML parse error on tezos-chain/templates/nodes.yaml: error converting YAML to JSON: yaml: line 128: did not find expected alphabetic or numeric character                    
helm.go:84: [debug] error converting YAML to JSON: yaml: line 128: did not find expected alphabetic or numeric character                                                  
```

I tried to run the helm template tests and they are passing, so it's not a helm version issue. Any idea?

2022-03-17 08:45 UTC, elric1 commented
To include special characters in the YAML, we must quote them. I've done this and added `TEZOS_LOG` to our tests to prevent a regression.

2022-03-21 20:10 UTC, harryttd commented
Running helm template after checking out the branch:
```shell
helm template charts/tezos --debug
install.go:172: [debug] Original chart version: ""
install.go:189: [debug] CHART PATH: /Users/aryehharris/Desktop/tezos-k8s-copy/charts/tezos


Error: parse error at (tezos-chain/templates/_containers.tpl:117): unclosed action
helm.go:81: [debug] parse error at (tezos-chain/templates/_containers.tpl:117): unclosed action
```

2022-03-21 20:15 UTC, harryttd commented
It is difficult to visually parse a lot of this PR as the yaml logic is pretty complex. Indenting nested if statements, loops, etc. instead of linear stacking nested logic would be a big help in being able to review this.
Examples:
```yaml
{{- if not (hasKey .call_args "name") }}
{{- $_ := set .call_args "name" .call_args.type }}
{{- end }}
# To this
{{- if not (hasKey .call_args "name") }}
  {{- $_ := set .call_args "name" .call_args.type }}
{{- end }}
```
```yaml
{{- define "tezos.init_container.config_init" }}
{{- if include "tezos.shouldConfigInit" . }}
{{- $_ := set $ "call_args" (dict "type"           "config-init"
                                  "image"          "octez"
                                  "with_config"    1
                                  "localvars"      1
) }}
{{ include "tezos.generic_container" $ }}
{{- end }}
{{- end }}
# To this

{{- define "tezos.init_container.config_init" }}
  {{- if include "tezos.shouldConfigInit" . }}
    {{- $_ := set $ "call_args" (dict "type"           "config-init"
                                      "image"          "octez"
                                      "with_config"    1
                                      "localvars"      1
    ) }}
    {{ include "tezos.generic_container" $ }}
  {{- end }}
{{- end }}
```

2022-03-24 23:37 UTC, elric1 commented
I tried to indent all of the code and then realised that we're just dealing with a templating language here. It's actually a bit annoying, because you get errors like:
```
Error: INSTALLATION FAILED: YAML parse error on tezos-chain/templates/nodes.yaml: error converting YAML to JSON: yaml: line 22: did not find expected '-' indicator
```
which at first perplex you. But then you realise that in this sort of thing:
```
list:
  - thing1
  - thing2
  {{- if something }}
    {{- if something else }}
  - thing3
    {{- end }}
  {{- end }}
```
Because you indented the lines, you end up with lines which contain only 2 or 4 spaces which is not valid YAML in the middle of a list.

2022-03-25 05:16 UTC, harryttd requested changes
Great PR 🙏 

I have additions in https://github.com/chapeltech/tezos-k8s/pull/3. Would greatly appreciate a review.

One main comment on this PR to pay attention to is the use of call_args. I think this can be much simplified by just passing args directly to `includes` together with the global context.

2022-03-25 05:16 UTC, harryttd commented on charts/tezos/templates/_containers.tpl
> +     *    name           the name of the statefulset, defaults to type
Do you mind please clarifying what both type and name are? I'm not sure i understand how they relate to each other and how name would default to type. So theoretically the name of the statefulset could become `wait-for-dns`?
Do you mean name of container by any chance?

2022-03-25 05:16 UTC, harryttd commented on charts/tezos/templates/_containers.tpl
> +     * onto the prior line in some cases.
I think this note can be edited due to my changes in https://github.com/chapeltech/tezos-k8s/pull/3

2022-03-25 08:22 UTC, elric1 commented on charts/tezos/values.yaml
> +##          all containers.  The most specific wins.
nodes.yaml might be better because they're listed there in a way that's relatively easy to see?

2022-03-25 15:38 UTC, harryttd commented on charts/tezos/values.yaml
> +##          all containers.  The most specific wins.
Yes good idea. Let's provide github link to the nodes.yaml

2022-03-25 15:44 UTC, elric1 commented on charts/tezos/values.yaml
> +##          all containers.  The most specific wins.
Eventually, there are some use cases for non-devs, e.g. setting log levels. The `PS1` hacks that I mentioned earlier should mostly be for developers, because one hopes that a shell on the boxen is infrequently needed those not updating things.

2022-03-25 15:48 UTC, elric1 commented on charts/tezos/values.yaml
> +##          all containers.  The most specific wins.
I've added some verbiage.

2022-03-25 21:54 UTC, elric1 commented on charts/tezos/templates/_containers.tpl
> +     *    name           the name of the statefulset, defaults to type
Yes, that's a typo. This is to take care of baker-NNN-PsProto being the name of a container of type baker.

2022-03-25 21:55 UTC, elric1 commented on charts/tezos/templates/_containers.tpl
> +     * onto the prior line in some cases.
Yes, it can.

2022-03-25 21:57 UTC, elric1 commented on charts/tezos/templates/_containers.tpl
> +{{- else }}
Yeah, looks like I left tezedge out of the Brave New World Order and so this is currently like an appendix: not much use until I finish the rest at which point I'll have to put it in. Or, better stated, I forgot to finish the tezedge bit of the code.

2022-03-26 00:42 UTC, nicolasochem requested changes
I tried again.

I was able to remove the unsafe disclaimer at node_globals level and statefulset level. But I had to put the "Y" between quotes, otherwise it mutates into a "true" inside the container, which does not work.

Therefore I am requesting that you change the example in values.yaml comments to put the "Y" in quotes. Also, there appears to be a conflict.

2022-03-30 18:32 UTC, harryttd requested changes
Thank you for the recent changes. There are still some unaddressed things.

2022-03-30 18:32 UTC, harryttd commented on charts/tezos/templates/_containers.tpl
> +  {{- if not (eq $.node_vals.readiness_probe false) }}
This condition breaks on older versions of Helm and needs Nicolas's recent changes to fix
```
helm template charts/tezos
Error: template: tezos-chain/templates/nodes.yaml:34:12: executing "tezos-chain/templates/nodes.yaml" 
at <include "tezos.container.node" $>: error calling include: template: tezos-chain/templates/_containers.tpl:163:12: 
executing "tezos.container.node" at <eq $.node_vals.readiness_probe false>: error calling eq: incompatible types for comparison
```

2022-03-31 17:11 UTC, elric1 commented on charts/tezos/templates/_containers.tpl
> +    {{- end }}
So, I've looked at this, and I think that both secrets are only used by the config-generator container. As such, we can leave them together and I'll just eliminate access from logger, etc., which is unnecessary.

2022-03-31 17:39 UTC, harryttd commented on charts/tezos/templates/_containers.tpl
> +    {{- end }}
Ok sounds good. As long as the identities go only where they need to go and nowhere else.

2022-04-01 02:24 UTC, harryttd commented on charts/tezos/templates/_containers.tpl
> +    {{- end }}
Thank you for fixing the typo.

I understand that currently we only set the tezos secret for config-generator. But, shouldn't we be more precise by making setting identities independent upon if the with_secret var is set or not? What if another container needs the tezos secret but should not be getting the ids? It could be an easy thing to miss when creating a new container that the ids would also be mounted.

Couple of options are to either make a new argument for ids, or have a check in the generic container that checks for config-gen and adds ids to it. (I'm not sure i like either option. But, it would be cool if within a new container definition we could add specific fields that would be merged/added to the generic container output. I think it is possible but would require some fancy helm)

At the bare minimum, it should be made explicit ini comments that with_secret includes not just tezos secret but also the identities secret.

2022-04-01 07:15 UTC, elric1 commented
Re: separating the node identities from the other secrets. My thought was that the node identities are just one of the many secrets that we can configure. And the word "secrets" is a generic term and so I imagined that it would encompass all of the secrets. There are really only two secrets at the moment, account keys and the node identities. The former is much more sensitive than the latter.

2022-04-14 16:55 UTC, harryttd commented on charts/tezos/templates/_containers.tpl
> +    {{- end }}
I realized that we still create the secret which is meant to contain the accounts, even if there are no accounts specified in values.yaml. When that is fixed we should not be mounting the secret when it won't exist. So I think a check here for the existence of accounts might be appropriate.

2022-04-25 17:21 UTC, elric1 commented on charts/tezos/templates/_containers.tpl
> +    {{- end }}
I think that this might create the same conditional in two places which could make it harder to change. @harryttd and I have agreed for the time being to just say that we'll continue to always define tezos-secrets even if there are no defined accounts.

2022-05-09 22:41 UTC, nicolasochem approved these changes
The rewrite of _containers.tpl is very welcome. This file is now easy to read and no longer intimidating.

I have tested this PR with the following:
* unmodified mkchain
* mkchain with 2 nodes, 1 baker
* zerotier (it was broken, but for an unrelated reason. I opened another PR)

I have tested the actual feature being added. I created mkchain with no parameters then added:

```
   12 node_globals:                                                                                                                                                                  
   13   env:                                                                                                                                                                         
   14     all:                                                                                                                                                                       
   15       TEZOS_CLIENT_UNSAFE_DISABLE_DISCLAIMER: "Y"       
```

Then opened a shell to the container and verified that the disclaimer was gone.

I tried the same `env` functionality at statefulset level instead of `node_globals`. It works.

Adding the expect tests to CI is useful as well, for reasons explained in PR description.

I am less sure about moving the sidecar from `scripts` folder into the utils container: it means that it's hard-burned there and cannot be changed on the fly in a live cluster. I never had to do this for the sidecar, however. And I suppose there is a good reason to do it this way in the context of the aggressive refactoring. So it's fine.

Thank you very much for this contribution.

2022-05-10 05:56 UTC, harryttd requested changes

2022-05-10 21:08 UTC, elric1 commented
The force push did this:
```
: arioch; git diff  817b53a 2b5c6a6
diff --git a/charts/tezos/templates/_containers.tpl b/charts/tezos/templates/_containers.tpl
index 77bf455..38fb441 100644
--- a/charts/tezos/templates/_containers.tpl
+++ b/charts/tezos/templates/_containers.tpl
@@ -225,7 +225,7 @@
 {{- end }}

 {{- define "tezos.container.sidecar" }}
-  {{- if not (eq $.node_vals.readiness_probe false) }}
+  {{- if or (not (hasKey $.node_vals "readiness_probe")) $.node_vals.readiness_probe }}
     {{- include "tezos.generic_container" (dict "root"  $
                                                 "type"  "sidecar"
                                                 "image" "utils"
```

2022-05-10 21:32 UTC, elric1 commented
Again:
```
: arioch; git diff 34fea9a 09f626b
: arioch;
```
All we did with that force push was to move 886e14d and squash it into 00cd5a6. No difference to the resulting text files.

2022-05-10 21:42 UTC, elric1 commented on .github/workflows/ci.yml
>      needs: [lint_helm_charts, publish_containers]
I've updated this.

2022-05-10 21:43 UTC, harryttd approved these changes

2022-05-10 22:11 UTC, merged