Update schema for snapshots and tarballs
oxheadalpha/tezos-k8s pull request #394
Opened 2022-03-16 22:46 UTC by elric1

Our new schema separates setting the URLs from deciding when and
how to use them.

2022-03-16 23:14 UTC, elric1 commented
Please note that the helm lint failure is solved in my prior pull request #393 which I expect we will review and merge before this one. I will need to rebase a little in any case, but there's enough here to start a discussion of the approach.

2022-03-18 22:00 UTC, harryttd requested changes
great pr :)

2022-03-18 22:00 UTC, harryttd commented on charts/tezos/values.yaml
> +## - "snapshot": enum of "snapshot", "tarball", or "none" defaulting to none.
Tezos snapshots are named so aptly well, snapshots. So it has made naming and referencing things harder in regards to tarballs which are also snapshots, but not "tezos snapshots".

Can we use the word 'standard' in place of 'snapshot' as a value so we don't have this sort of self-referencing thing going on? I think the word gives us the right category term to differentiate between regular snapshots and tarballs.

2022-05-25 18:04 UTC, orcutt989 commented
Great PR thanks @elric1

2022-05-25 18:29 UTC, elric1 commented
Interesting, the tests operate not against the branch itself, but rather against the branch as merged against HEAD. I've rebased and force pushed because the tests needed the new default image to be v13-release.

2022-05-25 22:38 UTC, elric1 commented on charts/tezos/values.yaml
> +## - "snapshot": enum of "snapshot", "tarball", or "none" defaulting to none.
I put "none" in specifically rather than just let it be only null. That's how a node can sync from scratch even if a global value is set to use snapshots.

2022-05-25 22:39 UTC, elric1 commented on charts/tezos/templates/_helpers.tpl
> +  {{- if or (hasKey $.node_vals "snapshot")
This is commit `8b93d59d88`. I'll squash it in later because there's not need to immortalise the intermediate state.

2022-05-25 22:45 UTC, elric1 commented on utils/snapshot-downloader.sh
>  fi
d1843a9 should take care of this. The code has changed a bit since the initial comment, but you can see the intent.

2022-05-25 22:48 UTC, nicolasochem reviewed
From an usability perspective this is good, I like that I can just write a very small values.yaml for deploying an ithacanet baker, and the snapshots/tarball links are already set for you. No need to put them in your values file.

If I am using a custom/unknown chain I can still add a map under `snapshots:` with my chain name as key, and specify snapshots at will. It's a bit harder to use than today, but on the other hand I am not sure anyone is doing this.

2022-05-25 23:08 UTC, elric1 commented on charts/tezos/values.yaml
> +## - "snapshot": enum of "snapshot", "tarball", or "none" defaulting to none.
fae64dc renames snapshot to standard. We could consider other names, though, such as "tezos" or something like that. I don't have much of an opinion, though, I think that standard should be good enough.

2022-05-26 19:42 UTC, harryttd commented on charts/tezos/values.yaml
> +## - "snapshot": enum of "snapshot", "tarball", or "none" defaulting to none.
`snapshot: octez/tezos` can sound simply like "use a snapshot of the Tezos blockchain" as opposed to really differentiating between the type of snapshot, `standard` vs `tarball`. Tarball is also a Tezos snapshot of the blockchain just formatted differently. So i think leaving as `standard` would be fine IMO

2022-05-26 19:58 UTC, harryttd commented on charts/tezos/values.yaml
> +## - "snapshot": enum of "snapshot", "tarball", or "none" defaulting to none.
> I put "none" in specifically rather than just let it be only null. That's how a node can sync from scratch even if a global value is set to use snapshots.

Just making sure i understand. Wouldn't this work:
Instead of making jq return `null` if no snapshot is set, return either `empty` or empty string. And just check that `SNAPSHOT_TYPE` is `empty` / doesn't has a value set. If yes, then use the global value for snapshot.

Otherwise if values.y `snapshot: null`, then `null` is a valid option, `SNAPSHOT_TYPE == null`, and the following code would use `null` instead of `none`. 
```shell
case "$SNAPSHOT_TYPE" in
standard)	if [ "$HISTORY_MODE" = archive ]; then
		    bail "Standard snapshots can't do archive mode, " \
		         "use tarball instead."
		fi
		standard "$SNAPSHOT_URL";;
tarball)	tarball "$SNAPSHOT_URL";;
null)		;;
*)
```

If i'm looking at this correctly, wouldn't this be simpler than introducing a new value for the enum instead of relying on an existing yaml primitive?

2022-05-26 20:39 UTC, elric1 commented on charts/tezos/values.yaml
> +## - "snapshot": enum of "snapshot", "tarball", or "none" defaulting to none.
null and none are different. null means use the value from the higher level, none means do not use a snapshot at all. The reason that null means that it is that it typically indicates that at this level, no one made a decision. I.e.:
node_globals:
  snapshot: tarball
nodes:
  cape-town:
    snapshot: none
    instances:
      - {}
will start cape-town-0 with no snapshot. If I set it to null, then it would use a tarball.

2022-05-26 22:16 UTC, harryttd requested changes
Thank you for this great PR :) 

Please see my comments.

One additional thought is, perhaps organize the deprecated tests into a subfolder? Perhaps /test/charts/deprecated or something?

2022-05-26 22:16 UTC, harryttd commented on utils/snapshot-downloader.sh
> +  bail "Only a snapshot or tarball url may be specified per history mode."
Perhaps should have additional text? Saying something along the lines of this error applies only when using the deprecated fields.

2022-05-26 22:16 UTC, harryttd commented on utils/snapshot-downloader.sh
> -  exit 1
I think we still need a check like this after all of our logic checking where the url comes from. Saying, that if a snapshot type was specified for X history mode, then a url needs to exist for it. As far as i can tell, there is no check for this.

2022-05-27 09:18 UTC, elric1 commented on charts/tezos/templates/configs.yaml
> +	| default (get .Values.snapshots "default")
Oh, I put that in just in case you have an odd chain name like:
```
node_config_network:
  chain_name: https://teztnets.xyz/dailynet-2022-02-08
```
default matches any name. It's a decent thing to put in your own values.yaml file because you may not be setting up a number of different chains and therefore may not need to match chain names.
Whitespace is probably a tab, I use those a lot. We usually take them out of the YAML parts because they break things, but they make no difference inside `{{` and `}}`.
I expanded the tabs in c7b98ab which will be squashed before the release.

2022-05-27 09:38 UTC, elric1 commented on utils/snapshot-downloader.sh
> -  exit 1
Heh, well, curl will output 'No URL specified', but, perhaps a better error might be interesting. I've added this enhanced error reporting in bc04075.

2022-05-27 09:39 UTC, elric1 commented on charts/tezos/values.yaml
> +## NOTE: there is no "standard" for archive because it doesn't make sense.
Did this in d4fcd24.

2022-05-27 09:41 UTC, elric1 commented on charts/tezos/values.yaml
> +      tarball:  https://mainnet.xtz-shots.io/full-tarball
Or maybe add full snapshots to xtz-shots?

2022-05-27 19:46 UTC, harryttd commented on charts/tezos/values.yaml
> +      tarball:  https://mainnet.xtz-shots.io/full-tarball
yes :) But that takes some work on the snapshot engine side and would need to be coordinated.

2022-05-27 19:50 UTC, harryttd commented on charts/tezos/values.yaml
> +## NOTE: there is no "standard" for archive because it doesn't make sense.
https://github.com/oxheadalpha/tezos-k8s/blob/d4fcd24c489741446e1e3370a4f9e1eb880bf0ef/charts/tezos/values.yaml#L250
"it aren't" -> "it isn't"

2022-05-31 15:38 UTC, elric1 commented on charts/tezos/values.yaml
> +## NOTE: there is no "standard" for archive because it doesn't make sense.
5b1b27d

2022-05-31 15:40 UTC, elric1 commented on charts/tezos/values.yaml
> +      tarball:  https://mainnet.xtz-shots.io/full-tarball
e3bb84b

2022-05-31 15:49 UTC, elric1 commented on charts/tezos/templates/_helpers.tpl
> +  {{- if get (dict "standard" 1 "tarball" 1 "none" 1) $snapshotType | not }}
ecc7b15a7098

2022-05-31 17:32 UTC, harryttd requested changes

2022-05-31 17:32 UTC, harryttd commented on utils/snapshot-downloader.sh
> +*)		usage "$SNAPSHOT_TYPE must be 'standard', 'tarball',"
1.
```shell
│ + CMD=snapshot-downloader                                                                                                 │
│ + shift                                                                                                                   │
│ + exec /snapshot-downloader.sh                                                                                            │
│ Did not find a pre-existing blockchain.                                                                                   │
│ My nodes history mode: 'rolling'                                                                                          │
│ /snapshot-downloader.sh: line 111: usage: not found                                                                       │
│ Stream closed EOF for x/rolling-node-0 (snapshot-downloader)                                                              │
│                                                                                                                           │
│
```
2.
```shell
Did not find a pre-existing blockchain.                                                                                   │
│ + CMD=snapshot-downloader                                                                                                 │
│ + shift                                                                                                                   │
│ + exec /snapshot-downloader.sh                                                                                            │
│ My nodes history mode: 'rolling'                                                                                          │
│ s                                                                                                                         │
│ /snapshot-downloader.sh: line 114: or 'none'.: not found                                                                  │
│ Stream closed EOF for x/rolling-node-0 (snapshot-downloader)
```
<img width="502" alt="Screen Shot 2022-05-31 at 1 13 00 PM" src="https://user-images.githubusercontent.com/19419199/171233805-f1702ba6-1611-4e28-9220-86320bdb2f23.png">

2022-05-31 17:46 UTC, harryttd commented on charts/tezos/templates/configs.yaml
> +	| default (get .Values.snapshots "default")
FYI this works in Helm:
```yaml

snapshots:
  https://teztnets.xyz/mondaynet:
    rolling:
      tarball: https://....

node_config_network:
  chain_name: "https://teztnets.xyz/mondaynet"
```

Also do you mind clarifying: 
> It's a decent thing to put in your own values.yaml file because you may not be setting up a number of different chains and therefore may not need to match chain names.

I'm not sure i follow what this case means. Do you by any chance mean "you may ~not~ be setting up..."? What would a case look like where i would use default?

2022-05-31 18:15 UTC, elric1 commented on utils/snapshot-downloader.sh
> +*)		usage "$SNAPSHOT_TYPE must be 'standard', 'tarball',"
Hmmm, never hit that code path.

2022-05-31 18:25 UTC, elric1 commented on charts/tezos/templates/configs.yaml
> +	| default (get .Values.snapshots "default")
I suppose that the use-case for default isn't terribly strong. I am imaging that if you want to override the snapshot location in your own values file, then it's a little redundant to make you specify which chain that you are using---you've already done it. So, you can just use "default" rather than duplicating whatever chain name that you've used. It's not much of an optimisation, but, I put it in.

2022-05-31 19:00 UTC, harryttd commented on utils/snapshot-downloader.sh
> +*)		usage "$SNAPSHOT_TYPE must be 'standard', 'tarball',"
i made sure to test

2022-05-31 19:13 UTC, harryttd approved these changes

2022-06-08 16:31 UTC, nicolasochem reviewed
I tried this and it worked:

```
node_config_network:
  chain_name: "jakartanet"

tezos_k8s_images:
  utils: localhost/tezos-k8s-utils:dev
    #rolling_snapshot_url: https://jakartanet.xtz-shots.io/rolling
snapshots:
  jakartanet:
    rolling:
      standard: https://jakartanet.xtz-shots.io/rolling

images:
  octez: tezos/tezos:v13-release

nodes:
  rolling-node:
    runs:
      - octez_node
    instances:
      - is_bootstrap_node: true
        config:
          shell:
            history_mode: rolling
```

But the old method didn't work however:

```
node_config_network:
  chain_name: "jakartanet"

tezos_k8s_images:
  utils: localhost/tezos-k8s-utils:dev
rolling_snapshot_url: https://jakartanet.xtz-shots.io/rolling

images:
  octez: tezos/tezos:v13-release

nodes:
  rolling-node:
    runs:
      - octez_node
    instances:
      - is_bootstrap_node: true
        config:
          shell:
            history_mode: rolling
```

I thought we were preserving backward compatibility for now. Are we?

Also do we want ithacanet/jakartanet URLs from xtz-shots hardcoded too?

2022-06-08 16:53 UTC, elric1 commented
Hmmm, well, I did try to preserve backwards compat, but this is an edge case that I didn't test. What's going on here is that my logic is: if you do not define the snapshot type in the node config or node_globals, then I fall back to the old mechanism. _BUT_ what appears to happen here (which I didn't test for, obviously) is that even though you define a "rolling-node" statefulset, it doesn't override all of the defaults for it. That means that even though you didn't specify it in your values.yaml:
```
nodes:
  rolling-node:
    snapshot: standard
```
is specified.
I think that maybe I will have to change the sense of the conditional and make it s.t. if you define `rolling_snapshot_url`, etc, they will override the new mechanism. I'm not fond of that, because I'd rather see the new mechanism take priority over the old, but I don't see a way to do that whilst retaining backwards compat.

2022-06-08 22:00 UTC, nicolasochem requested changes
Thank you for explaining the issue I had with the old model. I think you are right and it's better to have the new model take precedence.

I think that if we provide default xtz-shots urls for mainnet, ithacanet and jakartanet, then most users will have to muck with these params or care about their existence. We should not spend extra effort just for bw compat. So let's just hardcode ithacanet and jakartanet and merge.

2022-06-10 16:56 UTC, nicolasochem commented
Another thought: this change restricts usage of snapshots to "known" chains which are hardcoded in octez (mainnet, jakartanet).

If someone wants to use tezos-k8s to create a totally private chain and maintains snapshots for this chain, then there is no longer any any way to pass this snapshot as parameter and bootstrap a private chain node from snapshot/tarball.

I don't think anyone is doing it, but did we consider this? Is it a problem?

2022-06-10 18:12 UTC, harryttd commented
@nicolasochem see Roland and my convo here: https://github.com/oxheadalpha/tezos-k8s/pull/394#discussion_r883064047

Does that answer your question?

2022-06-10 18:30 UTC, nicolasochem commented
@harryttd oh yes, it does. I guess it needs to be documented?

2022-06-14 14:57 UTC, elric1 commented
I want to make another proposal for the backwards compat mechanism.
As I mentioned above, I don't want `rolling_snapshot_url`, et al. at the top level override people's specific setting of:
```
nodes:
  rolling:
    snapshot: tarball
```
But, I do want to provide a default for the chart with just "rolling-node" defined.
Right now, `nodes-><name>->snapshot` is an enumerated type with "standard", "tarball", or "none" as possible values. I am going to propose that for backwards compat, I add a value of "compat" which has the semantics of: "standard" unless `rolling_snapshot_url` is defined in which case that value takes precedence. In this way, we will use the legacy values if `nodes-><name>->snapshot` isn't defined or if it is set to "compat". The difference between undefined and "compat" is that undefined means no snapshots unless the legacy url values are defined whereas "compat" means standard if they aren't defined.

2022-06-14 19:34 UTC, nicolasochem approved these changes
@elric1 the new proposal for handling backward compatibility sounds good, however I think we can merge this as is. The project would be in better shape with this merged, since users can now deploy testnet setups without specifying any URL at all. Then, why add code to handle the old-style parameters? Presumably, if a user has these parameters set, they would be set to the same values than the new defaults?

2022-06-14 22:59 UTC, harryttd commented
> @harryttd oh yes, it does. I guess it needs to be documented?

Let's add documentation

2022-07-15 21:27 UTC, nicolasochem commented
@elric1 let's wrap this up?
We need to add ghostnet support.

Additionally, this will enable a one-liner helm in the new [doc website](https://news.tezoscommons.org/double-baking-and-remote-signers-639bf8ef7e65): a single line of helm to install a ghostnet rolling node in a cluster (no values.yaml needed).

2022-12-17 05:14 UTC, nicolasochem commented
replaced by #525

2022-12-17 05:14 UTC, closed without merging