Add a "join_public_network" option
oxheadalpha/tezos-k8s pull request #408
Opened 2022-04-11 13:44 UTC by picojulien

When spawning resilience testnet, we are in a setup where we don't define a private network, as we are using mainnet contexts, but we don't want to join public network.

This MR add an option in the value file to prevent connection to public network.

2022-04-12 22:44 UTC, nicolasochem requested changes
We do have a bit of "magic" behavior under the hood: when passing a network name, tezos-k8s assumes the network is public, runs `config init` to extract the hardcoded boot nodes, then adds them to the node configuration generated by config-generator.

This PR disables this behavior for the yes-nodes use case. I do not see a better way to do it.

I suggested a change for the values.yaml comment. Otherwise, LGTM.

2022-04-12 22:44 UTC, nicolasochem commented on charts/tezos/values.yaml
> +# public one
```suggestion
# Setting node_config_network with a chain_name assumes the network is public.
# tezos-k8s will then configure the nodes to connect to boot-nodes for the selected chain.
# This may not always be desired. For example, you may want to run a mainnet replica
# in isolation with yes-nodes.
# Uncomment the line below to remove boot-node configuration from nodes on a public
# network. The nodes will not establish any connection outside of the cluster. 
```

2022-04-13 00:26 UTC, harryttd commented on utils/config-generator.py
> +THIS_IS_A_PUBLIC_NET = True if ((not NETWORK_CONFIG.get("genesis"))) else False
Line 55 should not contain any changes

2022-04-13 00:30 UTC, harryttd commented on utils/config-generator.py
> +    JOIN_PUBLIC_NETWORK =  THIS_IS_A_PUBLIC_NET
`.get` shouldn't ever throw an error. I don't think the try/except is necessary and it should be able to be simplified to:
```suggestion
JOIN_PUBLIC_NETWORK =  CHAIN_PARAMS.get("join_public_network", THIS_IS_A_PUBLIC_NET)
```

2022-04-13 00:40 UTC, harryttd commented on utils/config-generator.py
> +    JOIN_PUBLIC_NETWORK =  THIS_IS_A_PUBLIC_NET
I think we also need to do a more sophisticated check. Say `THIS_IS_A_PUBLIC_NET == False`, so we are spawning a new chain. But the user also set `JOIN_PUBLIC_NETWORK == True`. So it is a contradiction. We should probably throw an exception in this case.

2022-04-13 01:03 UTC, harryttd commented on charts/tezos/values.yaml
> +# public one
@nicolasochem Perhaps the new flag should moved under `node_config_network` to keep the context of these fields together?

When defining a private chain, the format isn't exactly as a node expects a config.json to be because of the `activation_account_name`. I think it would be ok to put the new flag under `node_config_network` too. In addition to your comment, it should be made clear that `genesis` and  `join_public_network` are mutually exclusive, and there should be an error check in Helm to fail hard and fast if the conditions contradict. Also see comment in config-generator.py in regards to doing this validation in the backend.

I think an appropriate place for this validation is here, and it should fail if both `genesis` and `join_public_network` are true. In fact this check should return false if `!genesis and !join_public_network`. config-init container doesn't need to run if you want to run a public network node without actually joining the chain: https://github.com/oxheadalpha/tezos-k8s/blob/293abe0de4eaa3bf9c405b88e2ee95fecbf3643f/charts/tezos/templates/_helpers.tpl#L82-L94

2022-04-13 01:04 UTC, harryttd requested changes
Thank you for this PR :) Please see my comments.

EDIT: I'm ok to take this over and to address my comments.

2022-04-14 15:56 UTC, picojulien commented on utils/config-generator.py
> +    JOIN_PUBLIC_NETWORK =  THIS_IS_A_PUBLIC_NET
Indeed. I amended my proposition.

2022-04-14 15:59 UTC, picojulien commented on utils/config-generator.py
> +    JOIN_PUBLIC_NETWORK =  THIS_IS_A_PUBLIC_NET
I'm not familiar with helm, so I don't know if we can push the check in the template, in order to fail earlier in the process ?

2022-04-15 22:12 UTC, harryttd commented
@picojulien It appears maintainers don't have access to your branch from your fork. So i can't add commits to this PR. Any way you can open up access on this PR so that i can push changes directly to your branch? Otherwise it makes it more complicated to add changes. I would likely need to make a new PR to get my changes in.

See: https://stackoverflow.com/a/57805943/6379084

2022-04-29 19:23 UTC, harryttd commented on charts/tezos/values.yaml
> +# public one
Actually after more investigation, It seems we should still run config-init, as a url to a network configuration can be passed as the `chain_name` in values.yaml. We need config-init to fetch the json blob to produce the config.json. If the value passed was simply just the name of the network, then we wouldn't need config-init to run. We could just get the network name directly from `chain_name`.

2022-05-09 23:48 UTC, nicolasochem approved these changes
It works. I was able to launch jakartanet locally and restore from tarball. When passing the following values.yaml, I observe that the chain does not connect to anything after boot:

```
node_config_network:
  chain_name: "jakartanet"
  join_public_network: false

tezos_k8s_images:
  utils: localhost/tezos-k8s-utils:dev
rolling_snapshot_url: https://jakartanet.xtz-shots.io/rolling

images:
  octez: tezos/tezos:v13-release

nodes:
  rolling-node:
    runs:
      - octez_node
    instances:
      - is_bootstrap_node: true
        config:
          shell:
            history_mode: rolling
```

Thank you for your contribution.

2022-05-09 23:54 UTC, merged