Snapshot bugfix
oxheadalpha/tezos-k8s pull request #411
Opened 2022-04-13 22:03 UTC by orcutt989

This fixes some bugs found with the snapshot-engine.

2022-04-13 22:55 UTC, nicolasochem approved these changes

2022-04-14 19:51 UTC, nicolasochem approved these changes
I didn't try, but it looks like everything is here. Thanks

2022-04-14 20:16 UTC, harryttd requested changes

2022-04-14 20:16 UTC, harryttd commented on charts/snapshotEngine/templates/snapshot-scheduler.yaml
> +                  key: SERVICE_ACCOUNT
Why in order to retrieve the value for service_account and image_name env vars does it need to go to the configmap? The configmap itself gets the values from values.yaml. Why don't you just get the values directly from there?

2022-04-14 20:16 UTC, harryttd commented on snapshotEngine/mainJob.yaml
> +                  key: SNAPSHOT_MARKDOWN_URL
SNAPSHOT_MARKDOWN_TEMPLATE_URL

2022-04-14 20:16 UTC, harryttd commented on snapshotEngine/snapshotMakerJob.yaml
> +                  key: SERVICE_ACCOUNT
why is this needed?

2022-04-14 20:20 UTC, orcutt989 commented on charts/snapshotEngine/templates/snapshot-scheduler.yaml
> +                  key: SERVICE_ACCOUNT
The service_account is used by yq for other templates.  We cannot pass these values into the yaml templates otherwise until the yaml files are turned into part of the helm chart.

2022-04-14 20:22 UTC, orcutt989 commented on snapshotEngine/snapshotMakerJob.yaml
> +                  key: SERVICE_ACCOUNT
Usd by YQ to pass into yaml manifests that are not in the helm template.

2022-04-14 20:24 UTC, harryttd commented on snapshotEngine/mainJob.yaml
> +                  key: SNAPSHOT_MARKDOWN_URL
you only fixed it in one spot.....

2022-04-14 20:26 UTC, orcutt989 commented on snapshotEngine/mainJob.yaml
> +                  key: SNAPSHOT_MARKDOWN_URL
Thanks got it now!

2022-04-14 20:26 UTC, harryttd commented on charts/snapshotEngine/templates/snapshot-scheduler.yaml
> +                  key: SERVICE_ACCOUNT
not sure i follow. We are in the snapshot-scheduler which gets deployed directly by helm. Hence it can reference values just like it is currently doing so for namespace and history mode.

2022-04-14 20:27 UTC, orcutt989 commented on charts/snapshotEngine/templates/snapshot-scheduler.yaml
> +                  key: SERVICE_ACCOUNT
Yes you're right thanks.

2022-04-14 20:29 UTC, harryttd commented on snapshotEngine/snapshotMakerJob.yaml
> +                  key: SERVICE_ACCOUNT
I don't see it being used in the snapshot-maker.sh script

2022-04-14 20:31 UTC, orcutt989 commented on snapshotEngine/snapshotMakerJob.yaml
> +                  key: SERVICE_ACCOUNT
https://github.com/oxheadalpha/tezos-k8s/blob/snapshot-bugfix/snapshotEngine/snapshot-maker.sh#L175-L176

2022-04-14 20:39 UTC, harryttd commented on snapshotEngine/snapshotMakerJob.yaml
> +                  key: SERVICE_ACCOUNT
Great, thanks for pointing it out.

just fyi, instead of picking each individual key off of a configmap, you can pass the whole configmap to set all the env vars within at once

2022-04-14 20:45 UTC, harryttd approved these changes
thank you. please squash and delete branch

2022-04-14 20:46 UTC, merged