add explanatory comments to snapshotEngine's values.yaml
oxheadalpha/tezos-k8s pull request #415
Opened 2022-04-13 22:54 UTC by nicolasochem

also replace `v12.2` with `v12-release` to follow tezos-k8s convention

2022-04-13 23:13 UTC, harryttd requested changes
Thank you for the great comments

2022-04-13 23:13 UTC, harryttd commented on charts/snapshotEngine/values.yaml
>  chainWebsiteMarkdown: ""
Thank you for the comment. 
Do we agree from slack convo to name this something like `jekyllSnapshotTemplateUrl`?

2022-04-13 23:13 UTC, harryttd commented on charts/snapshotEngine/values.yaml
> +# Specify this role below.
```suggestion
# snapshotEngine containers interact with the kubernetes control
# plane to create volume snapshots. This requires a special IAM role
# so k8s can create the snapshots and volumes in the cloud.
# Specify this role below.
```
good? I believe that's how it works.

2022-04-13 23:13 UTC, harryttd commented on charts/snapshotEngine/values.yaml
> +# to generate all artifacts.
Thank you for the great comment.

This sentence is true, although i think it might imply it is necessary to deploy both rolling and archive nodes. But a user can choose to deploy one or the other. They are mutually exclusive.

2022-04-13 23:13 UTC, harryttd commented on charts/snapshotEngine/values.yaml
> +# class `snapshot-archive-node` and `snapshot-rolling-node`.
good?
```suggestion
# The default configuration below will be looking for tezos nodes defined in the 
# tezos chart with class names `snapshot-archive-node` and `snapshot-rolling-node`. 
# If you'd like to name them differently, make sure to match the names in both the 
# tezos chart and here in the snapshot engine chart. 
# Also, the tezos-k8s chart names the node data volume 'var-volume' by default.
```

2022-04-13 23:15 UTC, nicolasochem commented on charts/snapshotEngine/values.yaml
>  chainWebsiteMarkdown: ""
I just wrote a ticket for this after thinking about it https://github.com/oxheadalpha/tezos-k8s/issues/416

2022-04-13 23:17 UTC, nicolasochem commented on charts/snapshotEngine/values.yaml
> +# to generate all artifacts.
You mean they are not mutually exclusive? Right now in oxheadinfra we are deploying both.

We have not really tested deploying one without the other, so I think we are ok?

2022-04-13 23:21 UTC, harryttd commented on charts/snapshotEngine/values.yaml
> +# to generate all artifacts.
Ah sorry , yes meaning you don't need both. It fine with deploying only one. If a user wants a website, they can write it to just handle one history mode.

Logically it would work. For each class defined in yaml, we create 2 new deployments, the warmer and the scheduler. The diff node classes don't relate at all to one another. They get separate deployments that target only their respective node with matching history mode.

2022-04-14 01:35 UTC, harryttd approved these changes

2022-04-14 01:55 UTC, orcutt989 approved these changes
Thank you

2022-04-14 03:55 UTC, merged