Docusaurus documentation site
oxheadalpha/tezos-k8s pull request #426
Opened 2022-04-18 18:35 UTC by orcutt989

This PR creates the initial build pipeline and site structure for a docusaurus-based documentation site for tezos-k8s.

2022-04-19 18:30 UTC, nicolasochem requested changes
Lets' not put the default blog post and images there? Let's just have one blank page named "tezos-k8s documentation?"

Also do we want to deploy on release or on push? I think deploying on release makes more sense, but we should deploy on push for now just to see that the pipeline works.

2022-04-20 19:12 UTC, nicolasochem submitted a review, later dismissed

2022-04-20 19:12 UTC, nicolasochem commented on .github/workflows/docusaurus.yml
> +  push:
Can we only deploy documentation during releases? We don't want unreleased features to be there.

2022-04-20 19:12 UTC, nicolasochem commented on docusaurus/src/pages/index.md
> +# Tezos K8s
Can this page move to the top level of the repo under `docs/` folder? So it's easier for contributors to find.

2022-04-20 19:19 UTC, orcutt989 commented on .github/workflows/docusaurus.yml
> +  push:
Done

2022-04-20 19:19 UTC, orcutt989 commented on docusaurus/src/pages/index.md
> +# Tezos K8s
Done

2022-04-20 19:38 UTC, nicolasochem submitted a review, later dismissed
thank you

2022-04-20 23:57 UTC, nicolasochem reviewed
there are 2 nojekyll files, normal?

2022-04-21 00:05 UTC, nicolasochem approved these changes
thanks!

2022-04-21 00:35 UTC, merged