WIP fix #416 remove the hardcoding from jekyll generation
oxheadalpha/tezos-k8s pull request #438
Opened 2022-05-04 00:04 UTC by nicolasochem

2022-05-05 16:42 UTC, harryttd requested changes
Great PR :)

- I'm assuming this is tested works?
- Do we want to make deploying a website optional? That might be too much work right now. I'm not sure.
- A user may not want a custom domain for their site and might just want to use a raw url to the bucket. Do we want to handle this now?

2022-05-05 16:42 UTC, harryttd commented on snapshotEngine/mainJob.yaml
> +                  key: JEKYLL_REMOTE_THEME_REPOSITORY
As a suggestion: The values from the configMap can be picked and ranged over instead of having to repeat these blocks of env vars 5 times. Additionally if we don't care about polluting the env vars of the container, the entire config map can be mounted at once with `envFrom`.

2022-05-05 16:42 UTC, harryttd commented on snapshotEngine/zip-and-upload.sh
> +            "url": "https://${NETWORK}.${SNAPSHOT_WEBSITE_DOMAIN_NAME}/${ARCHIVE_TARBALL_FILENAME}",
The url can be defined as a variable by prefixing `https` with `S3_BUCKET` and used across this file, appending the filename each time.

2022-05-05 16:42 UTC, harryttd commented on snapshotEngine/zip-and-upload.sh
> +
I can't leave a comment on line [541](https://github.com/oxheadalpha/tezos-k8s/pull/438/files#diff-54485a3da425f8ab97a77059aa9b26d885e1f0c46e95c0f1ad8938625f9d9ffeR541) as it isn't part of the diff, but `config` should be removed from the comment.

2022-05-05 16:43 UTC, harryttd commented on snapshotEngine/mainJob.yaml
> +                  key: JEKYLL_REMOTE_THEME_REPOSITORY
Never mind picking and ranging bec this file is not helm templated. But the configmap is able to be mounted with envFrom.

2022-05-06 00:07 UTC, nicolasochem commented on snapshotEngine/mainJob.yaml
> +                  key: JEKYLL_REMOTE_THEME_REPOSITORY
what do you mean by "picking and ranging"?

2022-05-06 00:22 UTC, harryttd commented on snapshotEngine/mainJob.yaml
> +                  key: JEKYLL_REMOTE_THEME_REPOSITORY
something along these lines:
```yaml
env:
{{ rang k, v := pick .Values "a" "b" }}
 - name: k
   value: v
 {{ end }}
```

2022-05-06 00:32 UTC, harryttd commented on snapshotEngine/zip-and-upload.sh
> +
sorry i missed line 575 also. has xtz-shots.io.

2022-05-06 00:32 UTC, harryttd approved these changes
i left one more comment but skip if you want

2022-05-06 04:01 UTC, nicolasochem commented
> * I'm assuming this is tested works?

Now yes. It's deployed on ithaca-shots. Here is the new metadata:

```
nochem@fedora ~/workspace/pulumi-polkadot/charts/plenty-bridge () $ curl -Ls https://ithacanet.xtz-shots.io/rolling-tarball-metadata
{
  "block_hash": "BLiT1qiY15DVM3p23KKNDGrQH3aMS5VdDVipY9dDXjk3QUkUz8Z",
  "block_height": "492980",
  "block_timestamp": "2022-05-06T02:29:30Z",
  "filename": "tezos-ithacanet-rolling-tarball-492980.lz4",
  "url": "https://ithacanet.xtz-shots.io/tezos-ithacanet-rolling-tarball-492980.lz4",
  "sha256": "911222c63243baadca77900df1af650c9bde7a25ffdbb86f518de51fdc67ea53",
  "filesize_bytes": "92478089",
  "filesize": "88M",
  "tezos_version": "6e2037c9 (2022-04-07 12:44:15 +0200) (12.3)",
  "chain_name": "ithacanet",
  "history_mode": "rolling",
  "artifact_type": "tarball"
}
```

> * Do we want to make deploying a website optional? That might be too much work right now. I'm not sure.
> * A user may not want a custom domain for their site and might just want to use a raw url to the bucket. Do we want to handle this now?

No, let's defer until we are actually trying to deploy without a website. Thanks for approval.

2022-05-06 04:09 UTC, merged