Add support for external/remote signers
oxheadalpha/tezos-k8s pull request #448
Opened 2022-05-13 19:39 UTC by orcutt989

This allows for a value `signer` in values.yaml...

```yaml
accounts:
  archive-baking-node-0:
    bootstrap_balance: '4000000000000'
    is_bootstrap_baker_account: true
    key: edpk......
    signer: http://<POD-NAME>.<SERVICE-NAME>.<NAMESPACE>:6732/<HASH>
    type: secret
```

That allows for an external/remote signer, including a signer in a different namespace.  This is specifically related to our securing the hot wallet, and eventually the KMS wallet. We will restrict who can shell into the signer pod by separating it out into its own namespace.

Note - Magic numbers 0x01 will need to be parameterized for testnets (dailynet for example), as activation is blocked with the current functionality. @nicolasochem is currently working on a PR for this

2022-05-16 19:25 UTC, harryttd requested changes

2022-05-16 19:25 UTC, harryttd commented on utils/config-generator.py
> +            sk = remote_signer(account_name, account_values.get("signer", None), key)
shouldn't need to pass the value as a new argument if you just check the value of a variable
`signer_url or remote_signer(...)`

2022-05-16 19:25 UTC, harryttd commented on utils/config-generator.py
> +            if account_key_type == "secret" and "signer" not in account_values:
based on a previous comment, type secret should not have a signer_url field. Only type public.

2022-05-16 19:25 UTC, harryttd commented on utils/config-generator.py
> +        if "signer" in account_values:
the signer url should be retrieved just once in this whole function and referenced as a variable. Instead of doing `"signer" in account_values` and `account_values.get("signer", None)` many times, and passing in the value to other functions to do the same check.

2022-05-16 19:43 UTC, nicolasochem commented on charts/tezos/values.yaml
> +# NOTE - type must be secret and signer must be URL to external remote signer.
Yes to all except I am not sure about this one:

> a public key is being provided along with a signer url. So the account is of type public, not secret. It references a url for the signer which has the secret key. I'm assuming some other code will have to change because of this.

Yes it was partially an attempt to minimize config-generator code changes, and partially an attempt to map the way octez deals with remote signing. It puts the URL in "secret_keys.json". See the output of `tezos-client list known addresses` as well:

```
archive-baking-node-0: tz1ZyqSwMFrnZZX3Wi41tA3wqR6TdrCy5Myw (http sk known)
```

I suppose there are 2 ways to interpret "secret/public" in this case: "we can bake for this account" vs "the key type provided as part of this yaml blurb is public". I am inclined to merge this as is (with your suggested edits)

2022-05-16 22:37 UTC, harryttd commented on charts/tezos/values.yaml
> +# NOTE - type must be secret and signer must be URL to external remote signer.
I hope we get to a point where we can remove the `type` field in the first place and just infer the type of key from the key itself. `edsk = sk`, `edpk = pk`, etc, instead of us unnecessarily managing this.

But until then, my understanding is that we've been using `accounts` with the interpretation of defining `account` objects with properties revolving around the context of a key. A valid tezos key and not a reference or location to a key, such as url to a remote signer which hosts the key. A key is really the bottomline of what an account is. So defining key/account properties but not what you do with them.

So the values.yaml for deploying a standalone signer in ns X will define a secret key type account and an sk will be used. The key will be hosted directly on the signer that references it. The obj technically doesn't need fields like `bootstrap_balance`.

The corresponding account values in ns Y will define a pubkey type account and the pubkey will be used and hosted directly by the baker. Here you will need fields like bootstrap_balance to configure the account properly.

2022-05-16 22:42 UTC, nicolasochem commented on charts/tezos/values.yaml
> +# NOTE - type must be secret and signer must be URL to external remote signer.
> I hope we get to a point where we can remove the type field in the first place and just infer the type of key from the key itself. edsk = sk, edpk = pk, etc

I think we already have this? @elric1 mentioned that the `type: public` and `type: private` can be omitted. Then maybe the right way to resolve this is to totally ignore this field and mark it as deprecated and print out a warning that it's being ignored when helm encounters it.

2022-05-16 22:45 UTC, harryttd commented on charts/tezos/values.yaml
> +# NOTE - type must be secret and signer must be URL to external remote signer.
Config generator expects a type. Something like pytezos should be able to tell what type of key it is.

2022-05-16 22:47 UTC, nicolasochem commented on charts/tezos/values.yaml
> +# NOTE - type must be secret and signer must be URL to external remote signer.
See this: https://github.com/oxheadalpha/teztnets/blob/main/dailynet/values.yaml#L39-L46

2022-05-16 22:57 UTC, harryttd commented on charts/tezos/values.yaml
> +# NOTE - type must be secret and signer must be URL to external remote signer.
hmmm i looked over the code again and from i think even secret keys will work without defining the type. Bec the import_keys() will determine the key is secret or not. Very cool. It should be tested though. So yes that makes life easy if it works. We don't need `type` at all.

2022-05-17 11:03 UTC, elric1 commented on charts/tezos/values.yaml
> +# NOTE - type must be secret and signer must be URL to external remote signer.
Yes, what I did with type was to remove the requirement to set it. But, if you do set it, then I check to make sure that the provided key matches the type. I was thinking about removing the "type" logic entirely. Please feel free to do that with no objections from me.

2022-05-17 11:07 UTC, elric1 commented on charts/tezos/values.yaml
> +# NOTE - type must be secret and signer must be URL to external remote signer.
One additional comment: I'm not sure that it makes sense to include the hash in the URL. Maybe something like:
  key: edpk...
  url: http://....
And then the code generates the tz[123]... to postpend to the URL might be better. We already work out the pk hash from the pk in the code using pytezos and so this is available.
Doing it this way would make it s.t. there is just one less thing to put in the config file that has to match another thing or an obscure annoying error occurs down the line.

2022-05-17 16:19 UTC, harryttd commented on charts/tezos/values.yaml
> +# NOTE - type must be secret and signer must be URL to external remote signer.
Very good point

2022-05-23 06:03 UTC, nicolasochem commented
I addressed some review comments. The suggestion to remove the hash from the URL has been implemented. The suggestion to deprecate key types in values.yaml has been implemented in another PR which is now the target of this one.

We still don't have a solution for passing signer env vars. Aryeh has one in his branch which has not pushed yet. So, for the time being we need to carry an additional commit to allow the additional magic byte 0x01 for activation.

2022-05-23 17:45 UTC, harryttd commented on charts/tezos/values.yaml
> +# NOTE - type must be secret and signer must be URL to external remote signer.
Either it or something along the comments section i suggested should be used
```
## A public key account can contain a url to a remote signer that signs with the 
## corresponding secret key. You shouldn't need to set this if you're deploying
## a tezos-k8s chart's signer into the same namespace. See the `signers` values 
## field below in the file to define remote signers.
```

2022-05-23 17:48 UTC, harryttd commented on charts/tezos/values.yaml
> +# NOTE - type must be secret and signer must be URL to external remote signer.
also the comment about `signer_url` should be used as the field instead of `signer` needs to be addressed

2022-05-23 18:10 UTC, harryttd requested changes
also a couple of points to still be addressed here: https://github.com/oxheadalpha/tezos-k8s/pull/448#discussion_r874013884

2022-05-23 18:10 UTC, harryttd commented on utils/config-generator.py
> +            if sk == None or pod_requires_secret_key(account_name, account_values):
I'm thinking out loud on this one. Not sure i'm correct: 
Why pass account values to this function to then check if signer exists on the account, when it has already been checked above and defaulted to None? Also `remote_signer` returns None if there are no signers so why isn't the current `if` statement sufficient? If there is no sk means there is no signer either. So then the regular function check, if the pod is activating/signing, should be enough.

2022-05-23 18:43 UTC, harryttd commented on charts/tezos/values.yaml
> +# NOTE - signer_url must be URL to external remote signer without any path.
What if someone creates a remote signer who's api has paths in urls? `https://my-signer.com/path-to-specific-signer-or-something/<pubkey_hash>` Shouldn't that work?

2022-05-23 19:36 UTC, nicolasochem commented on charts/tezos/values.yaml
> +# NOTE - signer_url must be URL to external remote signer without any path.
right, let me be more specific

2022-05-23 21:29 UTC, nicolasochem commented on utils/config-generator.py
> +            if sk == None or pod_requires_secret_key(account_name, account_values):
No, the problem is with activation. When I do as you describe, it's trying to use the local key for activation and fails because the public key is set instead of the private key. Without looking too much into why it is the case, I suggest we leave it as is.

2022-05-24 00:22 UTC, nicolasochem approved these changes
I addressed the rest of the review comments and observed it is still working in these 3 cases:

* no signer
* internal remote signer
* external remote signer in a different namespace

2022-05-24 00:24 UTC, harryttd approved these changes

2022-05-24 00:26 UTC, merged