Set per-block-votes from values.yaml
oxheadalpha/tezos-k8s pull request #456
Opened 2022-05-24 16:57 UTC by nicolasochem

This gives a tezos-k8s baker the ability to set per-block votes in the
`protocols` section of values.yaml

It is also made mandatory: when this is unset, the baker will give a
useful error message.

This fits the tzip recommendation of not giving a default choice to the
user.

I verified with [MR 5390](https://gitlab.com/tezos/tezos/-/merge_requests/5390) that it
works properly: when set, the baker starts. When unset, it gives the
user suggestions on how to set it.

For now, voting is global. Custom votes per baker will be supported
later, by allowing an override of `protocols` at statefulset instance
level.

I am leaving as draft. We need to wait for 13.1 to release this.

Note: when we move mkchain to support jakarta by default, we should set
a pass vote. For private chains, it's fine to set a default.

2022-07-15 21:55 UTC, nicolasochem commented
Update: it works on octez 14.0 and kathmandunet is using this PR as submodule, [here is the config](https://github.com/oxheadalpha/teztnets/blob/main/kathmandunet/values.yaml#L243-L249)

We can merge once 14.0 is final (this will break compat with 13.0)

2022-08-12 18:17 UTC, orcutt989 approved these changes
Cool! Thanks! 🔥

2022-08-16 22:48 UTC, harryttd requested changes

2022-08-16 22:48 UTC, harryttd commented on charts/tezos/values.yaml
> +  ## * command: the suffix of the tezos-baker binary
prefix?

2022-08-16 22:48 UTC, harryttd commented on charts/tezos/values.yaml
> +  ##   "on" and "off" must be between quotes.
what about pass?

in the alpha proto below it is set as pass.

2022-08-16 22:48 UTC, harryttd commented on charts/tezos/values.yaml
> +  ## to make an explicit educated choice on every toggle.
Does this mean that a one command deployment of the chart won't work anymore?

2022-08-16 22:48 UTC, harryttd commented on charts/tezos/scripts/baker.sh
> +if [[ "$tezos_version" == *"13"* ]]; then
the client command also outputs a hash and date. Isn't it possible for them to contain "13"? Or being that they don't at the current time, we will eventually remove this code and it doesn't matter. What about v14 tho? I

2022-08-16 23:08 UTC, nicolasochem commented on charts/tezos/values.yaml
> +  ## to make an explicit educated choice on every toggle.
Yes it will, because the command deploys a node, not a baker, which works out of the box.

2022-08-17 06:20 UTC, nicolasochem commented on test/charts/private-chain.expect.yaml
> +# Source: tezos-chain/templates/configs.yaml
done

2022-08-17 06:20 UTC, nicolasochem commented on charts/tezos/values.yaml
> +  ## * command: the suffix of the tezos-baker binary
suffix like `tezos-baking-013-PtJakart`

2022-08-17 06:21 UTC, nicolasochem commented on charts/tezos/values.yaml
> +  ##   "on" and "off" must be between quotes.
pass needs not be between quotes. the problem with "on" and "off" is that yaml (or helm) interprets it as true or false.

2022-08-17 06:24 UTC, nicolasochem commented on charts/tezos/scripts/baker.sh
> +if [[ "$tezos_version" == *"13"* ]]; then
fixed by matching to 13.0. I don't expect any new v13 release at this point, so it works.

2022-08-17 19:56 UTC, harryttd commented on charts/tezos/values.yaml
> +  ## * command: the suffix of the tezos-baker binary
ah my bad

2022-08-19 17:06 UTC, harryttd commented on charts/tezos/templates/nodes.yaml
> +        - name: per-block-votes
Shouldn't this also need the hasPerBlockVotes check? If the configmap doesn't exist it will fail to mount.

2022-08-25 17:24 UTC, nicolasochem commented on charts/tezos/templates/nodes.yaml
> +        - name: per-block-votes
My bad. Fixed and I tested both baker and regular node on minikube.

2022-08-25 19:18 UTC, harryttd commented on charts/tezos/templates/NOTES.txt
> +WARNING: you did not specify the liquidity baking toggle vote in "protocols" for protocol "{{ $p.command }}", your baker will not start.
Sorry I didn't notice earlier. Should we fail instead of warning being the baker will fail anyways? Just exit early in helm?

2022-08-25 19:22 UTC, nicolasochem commented on charts/tezos/templates/NOTES.txt
> +WARNING: you did not specify the liquidity baking toggle vote in "protocols" for protocol "{{ $p.command }}", your baker will not start.
OK. Another issue is that when you are not a baker, the warning/error should not be thrown. So I need to rework this a bit.

2022-08-25 19:34 UTC, harryttd commented on charts/tezos/templates/NOTES.txt
> +WARNING: you did not specify the liquidity baking toggle vote in "protocols" for protocol "{{ $p.command }}", your baker will not start.
Perhaps the check for bakers could be with Roland's code for creating the baker container. 

'''yaml

{{- define "tezos.container.bakers" }}
  {{- if has "baker" $.node_vals.runs }}
    {{- $node_vals_images := $.node_vals.images | default dict }}
    {{- range .Values.protocols }}
      {{- $_ := set $ "command_in_tpl" .command }}
      {{- include "tezos.generic_container" (dict "root" $
                                                  "name" (print "baker-"
                                                          (lower .command))
                                                  "type"        "baker"
                                                  "image"       "octez"
      ) | nindent 0 }}
    {{- end }}
  {{- end }}
{{- end }}
'''

2022-08-25 19:54 UTC, nicolasochem commented on charts/tezos/templates/NOTES.txt
> +WARNING: you did not specify the liquidity baking toggle vote in "protocols" for protocol "{{ $p.command }}", your baker will not start.
Done. As a consequence, Ithaca w/o flag no longer works, but I think that's fine, it's an old protocol.

2022-08-26 19:01 UTC, harryttd approved these changes
Awesome :) I'm assuming works as a submod in OI. Did not test the latest commits myself

2022-08-26 22:16 UTC, merged