Generate a genesis block when omitted from config
oxheadalpha/tezos-k8s pull request #470
Opened 2022-07-06 19:53 UTC by nicolasochem

The chain id is deterministically generated from the genesis block hash,
and it is important that every new public chain has a different one.
On teztnets, we accidentally gave the same block hash to half-baked
kathmandunet and jakartanet.

To prevent this in the future, we add a tezos-k8s feature that generates
a genesis block hash when absent. It is derived from chain_name.

@elric1 had already written some code for that but it was gated by a
flag `should_generate_unsafe_deterministic_data`. The purpose of that
flag is to autogenerate deterministic well-known accounts for private
simulations. It also generates the genesis block hash, but that's not
unsafe per se. So I moved this code out of the flag. When the chain_name
is provided, it's using it as the seed, otherwise it uses "foo" as
before.

Mkchain now outputs a values.yaml without genesis block. It will be
generated with the method introduced here.

2022-07-07 00:45 UTC, harryttd commented on mkchain/tqchain/mkchain.py
> -from tqchain.keys import gen_key, get_genesis_vanity_chain_id, set_use_docker
we can remove the function from the file now that we aren't using it anymore

2022-07-07 01:04 UTC, harryttd requested changes

2022-07-07 01:04 UTC, harryttd commented on utils/config-generator.py
> +    fill_in_missing_genesis_block()
As a general thing, I don't think this should be run unless we are dealing with a private chain. As it isn't relevant otherwise.

Also, i do believe bec it is being run even on a public network, it will break. As the function tries to get `genesis` off of the network config, and it won't exist on a public net. (we shouldn't fix this by defaulting it to an empty object)

2022-07-07 02:35 UTC, nicolasochem commented on utils/config-generator.py
> +    fill_in_missing_genesis_block()
Running it on a public chain is the point here. I want to eliminate one step of teztnets creation, where I have to manually generate a genesis block. Instead, it will be autogenerated. This is relevant at activation.

If I give you my values with the Genesis block absent, you will regenerate it.

I need to convert this code into typescript so the output of teztnets also contains this genesis block. Otherwise people won't be able to run `--network https://teztnets.xyz/networkname`

If the network is well known and hardcoded into Octez, then it does not matter. The Genesis hash will be hardcoded too.

2022-07-07 02:39 UTC, nicolasochem commented on utils/config-generator.py
> +    fill_in_missing_genesis_block()
But, you are right that the code fails when the network is hardcoded i.e. mainnet. Let me fix this.

2022-07-07 03:37 UTC, nicolasochem commented on utils/config-generator.py
> +    fill_in_missing_genesis_block()
I tried with the following values and it worked, considering it resolved:

```
node_config_network:
  chain_name: "https://teztnets.xyz/ghostnet"

tezos_k8s_images:
  utils: localhost/tezos-k8s-utils:dev

rolling_tarball_url: "https://ghostnet.xtz-shots.io/rolling-tarball"
rolling_snapshot_url: null
```

2022-07-07 15:58 UTC, harryttd requested changes

2022-07-15 20:46 UTC, nicolasochem commented on utils/config-generator.py
> +    fill_in_missing_genesis_block()
With the last iteration of my code, `fill_in_genesis_block_hash` is only run if `THIS_IS_A_PUBLIC_NET` is false. (I don't like this denomination anymore after our discussion, I think it should be `THIS_IS_A_CUSTOM_NET` but anyway)

This function fail with an explanatory error msg when the chain name is not found instead of defaulting to `foo`.

I don't know why this default is here to begin with, perhaps octez fills in a chain name when none is provided. Anyway, to the best of my knowledge this default is not useful to anyone now).

2022-07-15 21:10 UTC, harryttd approved these changes

2022-07-15 21:22 UTC, merged