Monosite
oxheadalpha/tezos-k8s pull request #483
Opened 2022-08-30 15:29 UTC by orcutt989

2022-08-30 17:00 UTC, nicolasochem commented
Thanks, I think this code (and similar below) can go away: https://github.com/oxheadalpha/tezos-k8s/blob/master/snapshotEngine/zip-and-upload.sh#L66-L94

Also, do we still need a gemfile and a gemfile.lock in this repo since we are cloning xtz-shots-website completely?

2022-10-06 19:14 UTC, nicolasochem requested changes

2022-10-07 15:27 UTC, orcutt989 commented on snapshotEngine/mainJob.yaml
> -                  key: DISABLE_STORAGE_INIT_TIME
I'm mounting the whole configmap instead of mounting the individual env vars. The variable is still being used.

2022-10-07 15:28 UTC, orcutt989 commented on charts/snapshotEngine/scripts/snapshot-warmer.sh
> +if kubectl get asdfasf > /dev/null 2>&1; then
haha wow

2022-10-07 16:03 UTC, nicolasochem approved these changes
Thanks! I recommend to deploy form submod one last time before merging.

2022-10-11 16:27 UTC, merged