Tezos: New init container to upgrade storage
oxheadalpha/tezos-k8s pull request #486
Opened 2022-09-09 18:54 UTC by orcutt989

This PR adds an init container that runs `tezos-node upgrade storage --data-dir /var/tezos/node/data`.

This is being done ahead of kathmandu activation.

2022-09-12 15:39 UTC, nicolasochem approved these changes
LGTM, didn't try (but @orcutt989 claims it works on minikube)

2022-09-12 15:42 UTC, nicolasochem requested changes
LGTM, you just have to fix the tests (see `./bin/test-charts -h`)

2022-09-12 15:47 UTC, nicolasochem approved these changes
LGTM, didn't try (but @orcutt989 claims it works on minikube)

2022-09-12 15:49 UTC, merged

2022-09-12 20:05 UTC, harryttd commented
Question: It appears this container will always run regardless of any goal of spinning up nodes. For private chain, public testnets, snapshot engines, etc. Is this on purpose?  Say the image being run with the current storage does not need to be updated.

Is temporary for v13 and v14?

@orcutt989

2022-09-12 21:16 UTC, orcutt989 commented on charts/tezos/templates/_containers.tpl
> +                                           "localvars"   1
Thanks!

2022-09-12 21:21 UTC, orcutt989 commented
> Question: It appears this container will always run regardless of any goal of spinning up nodes. For private chain, public testnets, snapshot engines, etc. Is this on purpose?  Say the image being run with the current storage does not need to be updated.
> 
> 
> 
> Is temporary for v13 and v14?
> 
> 
> 
> @orcutt989 

Yeah it runs no matter what. We thought we would make it configurable later. For now it runs for a millisecond if it doest need an upgrade. @nicolasochem

2022-09-13 06:08 UTC, nicolasochem commented
Making it parametrizable is an annoyance for the user. Making it non
parametrizable creates an init container that is useless the majority of
the time.

I'd say we should focus on the user at the expense of yaml cleanliness.

On Mon, Sep 12, 2022, 11:21 PM Jimmy ***@***.***> wrote:

> Question: It appears this container will always run regardless of any goal
> of spinning up nodes. For private chain, public testnets, snapshot engines,
> etc. Is this on purpose? Say the image being run with the current storage
> does not need to be updated.
>
> Is temporary for v13 and v14?
>
> @orcutt989 <https://github.com/orcutt989>
>
> Yeah it runs no matter what. We thought we would make it configurable
> later. For now it runs for a millisecond if it doest need an upgrade.
> @nicolasochem <https://github.com/nicolasochem>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/oxheadalpha/tezos-k8s/pull/486#issuecomment-1244496874>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAAWXC2EYNFIKYU57RLJ7RTV56NEZANCNFSM6AAAAAAQI5RRBM>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>