Tezos signer forwarder
oxheadalpha/tezos-k8s pull request #498
Opened 2022-10-18 23:44 UTC by nicolasochem

The last remaining piece of https://github.com/midl-dev/tezos-on-gke/ to move into tezos-k8s, tezos-signer-forwarder is a terminating pod for ssh tunnels exposing a tezos signing endpoint from an on-prem location.

2023-07-20 03:42 UTC, harryttd requested changes
I have to finish reviewing a few things but submitting my current comments. Went through most of the PR but still need to understand better the services and statefulset "endpoints". I don't recall if we spoke about sts vs deployment for this PR or another one, but that is one thing i'm thinking about. As there is no state for the forwarders, and they don't appear to be scalable on the sts pods level, then why not just use a deployment.

2023-07-20 03:42 UTC, harryttd commented on charts/tezos-signer-forwarder/templates/statefulset.yaml
> +{{- $signer_metrics := .signer_metrics }}
I think the variables might be redundant. The values either need to be accessed with `.` or `$` so why not leave it with `.`.

2023-07-20 03:42 UTC, harryttd commented on charts/tezos-signer-forwarder/templates/statefulset.yaml
> +{{- $endpoint := index $signers.endpoints $i }}
I believe this can just be:
```suggestion
{{- range $i, $endpoint := .endpoints }}
```

2023-07-20 03:42 UTC, harryttd commented on charts/tezos-signer-forwarder/templates/statefulset.yaml
> +        midl_endpoint_name: {{ $endpoint.alias }}
remove `midl`?

2023-07-20 03:42 UTC, harryttd commented on charts/tezos-signer-forwarder/templates/statefulset.yaml
> +    "pulumi.com/skipAwait": "true"
not needed

2023-07-20 03:42 UTC, harryttd commented on charts/tezos-signer-forwarder/templates/config.yaml
> +{{- $endpoint := index $signers.endpoints $i }}
see similar comments on the statefulset

2023-07-20 03:42 UTC, harryttd commented on charts/tezos-signer-forwarder/templates/statefulset.yaml
> +    spec:
podSecurityContext should be set, and more k8s fields in general should be configurable, such as serviceAccountName. See kms signer [example](https://github.com/oxheadalpha/tezos-k8s/blob/a53fd7fb98a7b04982ed54c7135736afb3400cfd/charts/tezos/templates/tacoinfra-remote-signer/main.yaml#L97-L110)

2023-07-20 03:42 UTC, harryttd commented on charts/tezos-signer-forwarder/templates/statefulset.yaml
> +      containers:
Containers should not be allowed privilege  escalation, and all linux capabilities should be dropped unless they happen to be needed. See kms signer [example](https://github.com/oxheadalpha/tezos-k8s/blob/a53fd7fb98a7b04982ed54c7135736afb3400cfd/charts/tezos/templates/tacoinfra-remote-signer/main.yaml#L146-L150)

2023-07-20 03:42 UTC, harryttd commented on charts/tezos-signer-forwarder/scripts/signer_exporter.py
> +        probe = requests.get(f"http://localhost:{signer_port}{readiness_probe_path}")
Is it possible to have hangups for the signer, causing health checks to backup like we had with the tezos node [sidecar](https://github.com/oxheadalpha/tezos-k8s/pull/581)?

2023-07-20 03:42 UTC, harryttd commented on charts/tezos-signer-forwarder/scripts/signer_exporter.py
> +      prometheus node-expoter and custom probes (power status, etc)
```suggestion
      prometheus node-exporter and custom probes (power status, etc)
```

2023-07-20 21:20 UTC, harryttd commented on charts/tezos-signer-forwarder/templates/service.yaml
> +  sessionAffinity: ClientIP
not sure i follow why this is important. There could be say 2 signers signing for the same key, right? If so, why does it matter that the same signer is always targeted?

2023-10-24 20:37 UTC, nicolasochem commented on charts/tezos-signer-forwarder/templates/service.yaml
> +  type: LoadBalancer
LB since it accepts connection from a signer from anywhere on the internet.

2023-10-24 20:44 UTC, nicolasochem commented on charts/tezos-signer-forwarder/templates/secret.yaml
> +  name: tezos-signer-forwarder-secret-{{ .Values.name }}
no, I think helm always installs stuff in a specific namespace, and so does pulumi.

https://www.reddit.com/r/kubernetes/comments/uglbn3/should_i_define_the_namespace_metadata_info_on_my/

I've actually removed it wherever it was still set on this chart. I know it's different from all our other charts in this repo, so I'm ok to re-add them because of consistency, but by default I wouldn't because these lines don't do anything.

2023-10-24 20:48 UTC, nicolasochem commented on charts/tezos-signer-forwarder/templates/service.yaml
> +    midl_baker_name: {{ .name }}
done

2023-10-24 20:48 UTC, nicolasochem commented on charts/tezos-signer-forwarder/templates/service.yaml
> +    midl_baker_name: {{ .name }}
done

2023-10-24 20:49 UTC, nicolasochem commented on signerForwarder/Dockerfile
> +FROM alpine:edge
done

2023-10-24 20:54 UTC, nicolasochem commented on signerForwarder/Dockerfile
> +CMD ["/usr/sbin/sshd"]
done

2023-10-24 20:55 UTC, nicolasochem commented on signerForwarder/Dockerfile
> +
no, the signer user has no shell, so can't do much.

2023-10-24 20:58 UTC, nicolasochem commented on charts/tezos-signer-forwarder/values.yaml
> +  tezos_signer_forwarder: localhost/tezos-k8s-signerforwarder:dev
fixed

2023-10-24 20:58 UTC, nicolasochem commented on charts/tezos-signer-forwarder/values.yaml
> +  # monitoring_email:
fixed

2023-10-24 20:58 UTC, nicolasochem commented on charts/tezos-signer-forwarder/templates/servicemonitor.yaml
> +  - midl_endpoint_name
fixed

2023-10-24 20:59 UTC, nicolasochem commented on charts/tezos-signer-forwarder/values.yaml
> +# connectivity.
actually, it goes together, since only tezos-remote-signer-os exposes these metrics. Unless you are rebuilding these metrics yourself, but I prefer to assume that the chart user will also be using the os image on the other end.

2023-10-24 21:02 UTC, nicolasochem commented on charts/tezos-signer-forwarder/values.yaml
> +#load_balancer_ip:
done

2023-10-24 21:02 UTC, nicolasochem commented on charts/tezos-signer-forwarder/templates/prometheusrule.yaml
> +        description: 'Remote signer "{{`{{ $labels.midl_endpoint_name }}`}}" for baker "{{`{{ $labels.midl_baker_name }}`}}" has lost power'
done

2023-10-24 21:02 UTC, nicolasochem commented on charts/tezos-signer-forwarder/templates/alertmanagerconfig.yaml
> +    - name: midl_endpoint_name
done

2023-10-24 21:03 UTC, nicolasochem commented on charts/tezos-signer-forwarder/templates/statefulset.yaml
> +{{- $signer_metrics := .signer_metrics }}
because there is another nested loop, and then these values are inacessible within the inner loop unless I do this

2023-10-24 21:09 UTC, nicolasochem commented on charts/tezos-signer-forwarder/templates/statefulset.yaml
> +        midl_endpoint_name: {{ $endpoint.alias }}
done

2023-10-24 21:10 UTC, nicolasochem commented on charts/tezos-signer-forwarder/templates/statefulset.yaml
> +    "pulumi.com/skipAwait": "true"
yes, I'm using readiness probe to check if the tunnel is up, so I can have active-standby signers using k8s default behavior of sending traffic to ready pods. but some of them are cold standby, I don't want pulumi to wait for all tunnels to be ready.

2023-10-24 21:16 UTC, nicolasochem commented on charts/tezos-signer-forwarder/templates/config.yaml
> +{{- $endpoint := index $signers.endpoints $i }}
fixed

2023-10-24 21:18 UTC, nicolasochem commented on charts/tezos-signer-forwarder/templates/statefulset.yaml
> +          subPath: ssh_host_ecdsa_key
done

2023-10-24 21:26 UTC, nicolasochem commented on charts/tezos-signer-forwarder/templates/statefulset.yaml
> +           name: tezos-signer-forwarder-config-{{ $name }}-{{ $i }}
done

2023-10-24 21:27 UTC, nicolasochem commented on charts/tezos-signer-forwarder/templates/service.yaml
> +{{- $endpoint := index $signers.endpoints $i }}
done

2023-10-24 21:31 UTC, nicolasochem commented on charts/tezos-signer-forwarder/templates/service.yaml
> +    name: metrics
done

2023-10-24 21:43 UTC, nicolasochem commented on charts/tezos-signer-forwarder/templates/service.yaml
> +    name: metrics
actually reverted. There are 2 kind of metrics exposed by the hardware signer:

* metrics from the signer itself such as: is ledger connected? is it ready to sign?
* system metrics by the prometheus exporter

The boolean in values only indicates whether the latter (system metrics) are enabled, but the former always is, and we always scrape them.

2023-10-24 21:43 UTC, nicolasochem commented on charts/tezos-signer-forwarder/templates/statefulset.yaml
> +{{ tpl ($.Files.Get (print "scripts/signer_exporter.py")) $ | indent 12 }}
no, for the reason always above, we always scrape something. the only question is whether we scrape system metrics (ram, temperature etc)

2023-10-24 21:47 UTC, nicolasochem commented on charts/tezos-signer-forwarder/templates/statefulset.yaml
> +              key: tunnel_endpoint_port
fixed

2023-10-24 21:47 UTC, nicolasochem commented on charts/tezos-signer-forwarder/templates/config.yaml
> +  tunnel_endpoint_port: "{{ $endpoint.tunnel_endpoint_port }}"
fixed

2023-10-24 21:48 UTC, nicolasochem commented on charts/tezos-signer-forwarder/templates/service.yaml
> +  sessionAffinity: ClientIP
otherwise you risk double signing. the high watermark does not work across signers.

2023-10-24 23:46 UTC, nicolasochem commented on charts/tezos-signer-forwarder/templates/statefulset.yaml
> +           name: tezos-signer-forwarder-config-{{ $name }}-{{ $i }}
it didn't work, so I reverted. the sshd daemon needs to run as root and needs 444.

2023-10-25 01:48 UTC, nicolasochem commented on signerForwarder/Dockerfile
> +# add openssh and clean
yes, otherwise no `usermod` command below

2023-10-25 01:51 UTC, nicolasochem commented on charts/tezos-signer-forwarder/templates/statefulset.yaml
> +      containers:
I tried and I got

```
chroot("/var/empty"): Operation not permitted [preauth] 
```

2023-10-25 01:56 UTC, nicolasochem commented on charts/tezos-signer-forwarder/templates/statefulset.yaml
> +    spec:
I don't see the point. security context can't be modified since we need to run as root, and the service account is not needed. This is unlike kms where you need a service account to bind to IAM permissions to access the KMS.

2023-10-25 02:11 UTC, nicolasochem commented on charts/tezos-signer-forwarder/scripts/signer_exporter.py
> +        probe = requests.get(f"http://localhost:{signer_port}{readiness_probe_path}")
indeed. I fixed it.

2023-10-25 02:17 UTC, nicolasochem commented
@harryttd long story short, I was struggling with this a lot in the past, I've now rediscovered that sshd must run as root. It's not really meant to be used in containers, but it's possible to do so as long as you don't change the user. There is still an user (signer) but sshd assumes this identity when it starts. see https://superuser.com/a/1548482

I've addressed your other comments, thanks for them. Please re-review.

2023-11-10 14:35 UTC, harryttd commented on charts/tezos-signer-forwarder/templates/statefulset.yaml
> +    "pulumi.com/skipAwait": "true"
this annotation tho shouldn't be hardcoded in tezos-k8s chart. It's explicitly tying it to pulumi. One could deploy this chart without pulumi. The annotation should really be set via values.yaml

2023-11-10 14:40 UTC, harryttd commented on charts/tezos-signer-forwarder/templates/statefulset.yaml
> +           name: tezos-signer-forwarder-config-{{ $name }}-{{ $i }}
I believe this can also be mounted `readOnly: true`

2023-11-10 14:46 UTC, harryttd approved these changes
left a couple more comments. but otherwise approved. thanks

2023-11-10 23:31 UTC, merged