Service monitor
oxheadalpha/tezos-k8s pull request #501
Opened 2022-10-28 05:47 UTC by nicolasochem

Add a service monitor to target the new metrics endpoint of v14.

2022-10-31 19:52 UTC, orcutt989 approved these changes
Looks great! Declutter FTW.

2022-11-01 00:27 UTC, harryttd requested changes

2022-11-01 00:27 UTC, harryttd commented on charts/tezos/templates/_containers.tpl
> +      name: metrics
`{{- if .Values.serviceMonitor.enabled }}` ?

2022-11-01 00:27 UTC, harryttd commented on charts/tezos/templates/static.yaml
> +      name: p2p
I'm curious, why wasn't this needed before?

2022-11-01 00:27 UTC, harryttd commented on charts/tezos/templates/static.yaml
> +      name: metrics
`{{- if .Values.serviceMonitor.enabled }}` ?

2022-11-01 00:27 UTC, harryttd commented on charts/tezos/values.yaml
> +          metrics_addr: [ "0.0.0.0:9932" ]
Comment out? bec monitor is default not enabled

2022-11-01 00:27 UTC, harryttd commented on charts/tezos/templates/_containers.tpl
> +      name: metrics
`{{- if .Values.serviceMonitor.enabled }}` ?

2022-11-01 16:28 UTC, nicolasochem commented on charts/tezos/templates/static.yaml
> +      name: p2p
The metrics endpoint needs to be here so the servicemonitor can pick up the metrics. While debugging this, I noticed there was no endpoint associated with the p2p port either, so I added it. It never mattered, because:
* internally we target pods directly
* when we want external p2p access we deploy a different service anyway, of type `LoadBalancer`

I guess this service was pretty useless?

2022-11-01 16:32 UTC, nicolasochem commented
@harryttd answering all of your remaining comments at once:

I have enabled metrics collection by default on tezos-k8s, by choice.

I have also ensured that octez default config in tezos-k8s is exposing its prometheus port.

It's better this way, than making it dependent of `ServiceMonitor` being `enabled` in the values: you could want to scrape this ports with something else than the prometheus operator (for example a manually provisioned prometheus).

So then, we would have `metricsExposed: true` separate from `serviceMonitor: enabled: true` but I feel that it's simpler to have it enabled all the time. It's not a security concern (it stays within the cluster and you can't kill the node with such metrics requests, in theory)

A future `NetworkPolicy` in our chart will tighten security appropriately, I think.

2022-11-02 23:17 UTC, merged

2022-11-03 23:22 UTC, harryttd commented on charts/tezos/templates/static.yaml
> +      name: p2p
The service is a headless service. K8s then allows you to target each pod individually instead of creating a clusterIP that would load balance across the pods.

I wonder because ports are now defined, rpc port isn't, so would that break? i'm not sure i get why we need to set ports here. Being we can anyways target the pod and use the port number.

2022-11-03 23:34 UTC, nicolasochem commented on charts/tezos/templates/static.yaml
> +      name: p2p
I just tried mkchain with 2 bakers and 1 node, and nodes are peering with each other and everything is working. So, it didn't break. I'm not sure why p2p is here though. Maybe safe to remove.

RPC is served from a different service.

It makes sense to have a p2p service targeting several pods, because it's fine to load balance the p2p connections. But, I did forget that the purpose of this (headless) service was to be able to target pods individually.

Knowing that, maybe it would have been better to leave it alone, and set the metrics port on the rpc service.

I'm pretty sure I did this for a reason. Probably the service monitor would not work if the port was not named on the service.

2022-11-03 23:44 UTC, harryttd commented on charts/tezos/templates/static.yaml
> +      name: p2p
an example where we target a specific  pod rpc endpoints is indexers: https://github.com/oxheadalpha/tezos-k8s/blob/cb8eed6aa0d0627cc46ffc9986c6a5eca61be323/charts/tezos/values.yaml#L449

So we need to know that we can still target any port we want. If we can, i don't know why we need to specify any ports now. 9732, and the metrics port. As long as the sts pod containers are exposing the port.

It appears to me the tezos-service-monitor is load balancing across all nodes. Does this allow us to monitor each node individually instead of conflating each nodes' metric data together?

2022-11-03 23:47 UTC, nicolasochem commented on charts/tezos/templates/static.yaml
> +      name: p2p
![Screenshot from 2022-10-28 17-38-58](https://user-images.githubusercontent.com/93067/199855861-4675f20e-d59e-4690-ac98-fab7894a8586.png)

it's labeling per pods

2022-11-03 23:51 UTC, harryttd commented on charts/tezos/templates/static.yaml
> +      name: p2p
so every 15s it sends a request to /metrics and each pod will eventuallly be hit. What if there are many many pods? They won't have their metrics updated for a while.

2022-11-03 23:55 UTC, harryttd commented on charts/tezos/templates/static.yaml
> +      name: p2p
>So we need to know that we can still target any port we want. If we can, i don't know why we need to specify any ports now. 9732, and the metrics port. As long as the sts pod containers are exposing the port.

once we deploy this release, we can prob test rpc of a specific node just by sshing into another one. That is prob sufficient. And then we can also remove the ports from the headless svc later just so it isn't confusing why we are exposing some ports on the svc and not others. not a big deal

2022-11-03 23:55 UTC, nicolasochem commented on charts/tezos/templates/static.yaml
> +      name: p2p
I don't think that's what is going on. I am aware of "pod monitor" but I've never used it, ServiceMonitor is what I have been using.

See these heavily thumbed-up comments: https://github.com/prometheus-operator/prometheus-operator/issues/3119#issuecomment-610445145