Add reources management for nodes
oxheadalpha/tezos-k8s pull request #508
Opened 2022-11-12 19:56 UTC by puppetninja

This is a duplicated one of #502, PR generated from official repo branch to run all the CI jobs

2022-11-12 20:01 UTC, puppetninja commented on charts/tezos/templates/_containers.tpl
> +    {{- $sidecarResources := dict "requests" (dict "memory" "80Mi") "limits" (dict "memory" "100Mi") -}}
we hardcode a sidecar when readniess probe is not specified, follow the same way to set the resources part

2022-11-14 16:29 UTC, nicolasochem requested changes
This still requires "documentation" in the chart's default values.yaml 

What we typically do is provide a commented-out example in the values file, with some additional explanatory commentary.

2022-11-16 03:15 UTC, harryttd requested changes

2022-11-16 03:15 UTC, harryttd commented on charts/tezos/templates/_containers.tpl
> +    {{- end }}
I don't think this is needed. `node_vals` is already set on `$`, so it can be directly accessed in the generic container function. The function itself checks for the existence of a `resources` property on the `node_vals`.

This comment applies to the other similar changes in this file.

2022-11-16 03:15 UTC, harryttd commented on charts/tezos/values.yaml
> +#        memory: 9120Mi
- The indentations is off a little bit
- A comment should be left stating that currently resources are only set for node/baker.
- a comment for `resources` should be put under the  `# Params at the statefulset level:` section above. Perhaps put it under `storage_size`.

2022-11-16 03:17 UTC, harryttd commented on charts/tezos/templates/_containers.tpl
> +     *                   and limit, default value is an empty dict.
This shouldn't be needed. Just check for it on `$.node_vals`.

2022-12-12 16:41 UTC, nicolasochem commented on charts/tezos/values.yaml
> +#      limits:
Maybe the example limit should be set a 16Gi? Double of the request? We have not used limits so I don't want to give too low a value as an example...

2022-12-13 15:28 UTC, puppetninja commented on charts/tezos/values.yaml
>  #       - baker
done

2022-12-13 15:30 UTC, puppetninja commented on charts/tezos/templates/_containers.tpl
> +     *                   and limit, default value is an empty dict.
I added this as we use this to hardcode the resource managements for side also, so the resource management is set for the whole pod and can be applied for autoscaler policies

2022-12-13 15:31 UTC, puppetninja commented on charts/tezos/templates/_containers.tpl
> +     *                   and limit, default value is an empty dict.
so not just checking `$.node_vals` for the node per se is what I meant

2022-12-14 06:01 UTC, nicolasochem commented on charts/tezos/templates/_containers.tpl
> +      {{- if hasKey $.node_vals "resources" }}
it looks like you can simply pass `"resources" $.node.vals.resources` and if the key is absent it would pass null, and still work? So you can avoid setting $bakerParams at all and just modify the dict passed to `include "tezos.generic_container"`.

2022-12-14 06:07 UTC, nicolasochem reviewed
Why assign requests to the baker as well as the node? Then if you set requests of 3300Mi on a baking node, the pod actually requires 6600Mi. and more if you have more bakers. Can we set a request for the node only, so the value configured ends up being the total pod request?

2022-12-21 17:47 UTC, puppetninja commented on charts/tezos/templates/_containers.tpl
> +    {{- $sidecarResources := dict "requests" (dict "memory" "80Mi") "limits" (dict "memory" "100Mi") -}}
this is always part of the pod, only by adding the autoscaler can calculate the total resource consumption made by the pod

2022-12-21 17:47 UTC, puppetninja commented on charts/tezos/values.yaml
> +#        memory: 9120Mi
done

2022-12-22 21:38 UTC, nicolasochem commented
@harryttd @orcutt989 all issues resolved, please review again

2022-12-22 21:51 UTC, orcutt989 commented
@nicolasochem @harryttd There are still requested changes on this PR. Please dismiss them if they have been addressed.

2022-12-22 21:52 UTC, nicolasochem approved these changes

2022-12-22 21:53 UTC, harryttd commented
I'm reviewing right now

2022-12-22 22:07 UTC, nicolasochem commented on charts/tezos/templates/_containers.tpl
> +     *                   and limit, default value is an empty dict.
@harryttd the sidecar is also instantiated using generic_container, so resource have to be a parameter to the function. otherwise the sidecar would have the same resources than the actual node.

2022-12-22 22:39 UTC, harryttd requested changes
Almost ready. I think i understand the PR more fully now. I didn't get that the scaler wouldn't scale if it was targeting specific containers as opposed to the entire pod resources. So if it couldn't find any resources defined on any container it wouldn't scale.

2022-12-22 22:39 UTC, harryttd commented on charts/tezos/values.yaml
> +#     # See: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
```suggestion
#     # You can optionally set resources and limits for your octez node
#     # See: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
```

Also shouldn't this be on line 116 instead?

2022-12-22 23:01 UTC, puppetninja commented on charts/tezos/values.yaml
> +#     # See: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
Indeed

2022-12-23 18:40 UTC, harryttd approved these changes

2022-12-23 18:48 UTC, merged