Handle Metadata from xtz-shots
oxheadalpha/tezos-k8s pull request #525
Opened 2022-12-17 05:14 UTC by nicolasochem

This introduces under the hood "magic" to download the right snapshot for you, when using default values.

There was a previous attempt #394, however since then we have made some progress in formalizing the metadata at xtz-shots.io, to the point where it makes sense to introduce these changes instead.

The metadata file https://xtz-shots.io/tezos-snapshots.json is intended to become some sort of standard across ecosystem snapshot providers.

It provides a flat list of snapshots across tezos networks, containing size in bytes and sha256sum.

We introduce a new value `snapshot_source` which is defaulting to the xtz-shots metadata URL. I hope marigold will provide one such file soon as well.

When this file is set, config-generator will download it, and find the right snapshot, based on the network name and the octez version. It will then pass it to the node pods for download.

We also introduce `prefer_tarballs` which will make the nodes download a tarball instead of a snapshot. This defaults to False to preserve today's behavior.

The variables `full_snapshot_url` `archive_tarball_url` etc... still exist. They used to have default set to mainnet URLs from xtz-shots, but they default to null now.

If you set these variables, they will override the metadata behavior that we are introducing. As before, you can't set a value for snapshot and tarball of same history mode at the same time, or helm will error.

When using the new method, two new behaviors are introduced:

1. snapshot-downloader verifies the free space on the filesystem, and does not attempt to download if it is insufficient
1. after downloading, it will check the sha256sum against the one in metadata.

Now, our "quick start" guide will become more compelling: with just one line of helm, it will be possible to start a mainnet node, a ghostnet node, or any network on xtz-shots.

Test:

These 4 values yaml are provided as reference.

I tested them all on limanet (because artifacst are small and fast).

When it's merged and released, the `tezos_k8s_images` value can go and only `node_config_network:chain_name` needs to be set.

```
/# starts a limanet rolling node, downloads a snapshot, verifies checksum and unpacks it
tezos_k8s_images:
  utils: ghcr.io/oxheadalpha/tezos-k8s-utils:snapshot_metadata
node_config_network:
  chain_name: limanet
```

```
/# starts a limanet rolling node, downloads a tarball, verifies checksum and unpacks it
tezos_k8s_images:
  utils: ghcr.io/oxheadalpha/tezos-k8s-utils:snapshot_metadata
node_config_network:
  chain_name: limanet
prefer_tarballs: true
```

```
/# verify that old method of downloading tarball still works
tezos_k8s_images:
  utils: ghcr.io/oxheadalpha/tezos-k8s-utils:snapshot_metadata
node_config_network:
  chain_name: limanet
rolling_tarball_url: https://limanet.xtz-shots.io/rolling-tarball
rolling_snapshot_url: null
```

```
/# verify that old method of downloading snapshot still works
tezos_k8s_images:
  utils: ghcr.io/oxheadalpha/tezos-k8s-utils:snapshot_metadata
node_config_network:
  chain_name: limanet
rolling_tarball_url: null
rolling_snapshot_url: https://limanet.xtz-shots.io/rolling
```

I also tried a private chain with mkchain with no parameters. it works

I am updating the python version to 3.10 in utils because I wanted to use python's new `case` statement. I tried 3.11 but pytezos is broken, I opened a ticket and referenced it in the source code.

2022-12-27 20:38 UTC, harryttd requested changes

2022-12-27 20:38 UTC, harryttd commented on utils/snapshot-downloader.sh
> +      echo "Error: sha256 checksum of the downloaded file did not match checksum from metadata file." >&2
I may not be correct but just from looking at this code my understanding is that the snapshot file will still exist on the machine even if the SHA doesn't match and we exit. The container would then restart. 

If we are downloading a tezos-snapshot, i think it would just try to download again even though it was previously downloaded and exists on the machine. If it is a tarball then the node data dir is imported here and not in the snapshot-importer container. So this container would restart and `if [ -d "$node_data_dir/context" ]; then` at the top of this file would return true and would exit the container cleanly.

2022-12-27 20:38 UTC, harryttd commented on charts/tezos/scripts/snapshot-importer.sh
> +fi
should this be the first `if` done?

2022-12-27 21:23 UTC, nicolasochem commented on charts/tezos/values.yaml
> +rolling_tarball_url: null
The behavior you are suggesting is more confusing to the user, than what I have currently implemented.

2022-12-27 21:32 UTC, nicolasochem commented on charts/tezos/values.yaml
> +rolling_tarball_url: null
Also the vast majority of users will only ever need one artifact type per chart.

2022-12-27 21:50 UTC, nicolasochem commented on utils/config-generator.py
> +    octez_container_version = os.environ["OCTEZ_VERSION"]
you are right, and I wasn't aware that you could override the version in sts level field `images`.

In this case, I'd rather fix it separately? I think OCTEZ_VERSION env var should be set by helm to the true image of the pod. This requires a change in `_containers.tpl`, where `OCTEZ_VERSION` would not be coming from the configmap, instead it will be set directly in the pod by helm. @harryttd

2022-12-27 21:54 UTC, nicolasochem commented on utils/config-generator.py
> +            and octez_version in s["tezos_version"]
Thanks. If `octez_version` is none, that means that the regex failed to find `vNN` in the version field. That could mean that we are running an unreleased container (as is the case in mondaynet etc). At this point, `octez_verison in s["tezos_version"]` will always be False so it will loop over the whole list needlessly. But I think in this case it should still download an artifact. Therefore, I will be changing this code, so when `octez_version` is None, it won't try to match by version.

2022-12-27 22:01 UTC, nicolasochem commented on utils/config-generator.py
> +                return {}
ok, I am now throwing an error in this case

2022-12-27 22:02 UTC, nicolasochem commented on charts/tezos/scripts/snapshot-importer.sh
> +fi
yes

2022-12-27 23:17 UTC, harryttd commented on charts/tezos/scripts/snapshot-importer.sh
> +fi
could this be in the check above `if [ -f ${node_dir}/chain.snapshot.block_hash ]; then`?

2022-12-27 23:17 UTC, harryttd commented on utils/config-generator.py
> +    try:
Do we need to run this if no snapshot_src was found? We already know that no ovrride for a specific hist mode was set. And so if no snap_src was set either we don't need to loop through anything

I also don't see why we need to wrap this all in a try/except. If we use `.get()`, no lookups will fail. When we check for the `-1` snapshot we can default to null and just return the var.

2022-12-27 23:17 UTC, harryttd commented on utils/config-generator.py
> +    full_snapshot_url = os.environ["FULL_SNAPSHOT_URL"]
I'm thinking we might need .get() instead of just array access, similar to looking up chain_name. Bec if the vars are not found bec they were commented out in the config then we will error out.

2022-12-28 00:10 UTC, nicolasochem commented on utils/snapshot-downloader.sh
> +      echo "Error: sha256 checksum of the downloaded file did not match checksum from metadata file." >&2
you are right; in fact, it was not even erroring out. The exit statement was caught in the pipe and the program was showing success. I have now fixed this, when a tarball with wrong sha256sum is downloaded, it flushes everything then tries again.

2022-12-28 00:28 UTC, nicolasochem commented on utils/config-generator.py
> +    octez_container_version = os.environ["OCTEZ_VERSION"]
done, thanks for noticing this

2022-12-28 00:48 UTC, nicolasochem commented on charts/tezos/templates/configs.yaml
> +  PREFER_TARBALLS: "{{ .Values.prefer_tarballs }}"
You mean the quotes? when I remove them here's what helm gives me

```
Error: INSTALLATION FAILED: ConfigMap in version "v1" cannot be handled as a ConfigMap: json: cannot unmarshal bool into Go struct field ConfigMap.data of type string
```

2022-12-28 01:06 UTC, nicolasochem commented on utils/config-generator.py
> +    try:
If no snapshot_src was found, we return earlier, so this code is not accessed.

I removed the try/except and did as you said.

2022-12-28 01:07 UTC, harryttd commented on charts/tezos/templates/configs.yaml
> +  PREFER_TARBALLS: "{{ .Values.prefer_tarballs }}"
ok makes sense. Especially as you updated the code in config-gen to handle the str into a bool

2022-12-28 01:32 UTC, nicolasochem commented
I retested all scenarios listed in PR description with `bf43020`, it still works. I also tried with latest master branch build, but it fails for a separate reason. Please re-review @harryttd

2022-12-28 01:49 UTC, harryttd commented on utils/config-generator.py
> +    prefer_tarballs = os.environ["PREFER_TARBALLS"].lower() in ('true', '1', 't')
```suggestion
    prefer_tarballs = os.environ.get("PREFER_TARBALLS". "").lower() in ('true', '1', 't')
```

2022-12-28 01:49 UTC, harryttd commented on utils/snapshot-downloader.sh
> +      touch ${data_dir}/disk_space_failed
do we need to return from this function so that it doesn't continue to run if there isn't enough disk space?

2022-12-28 01:49 UTC, harryttd commented on utils/snapshot-downloader.sh
> +      touch ${data_dir}/sha256sum_failed
we should prob explicitly return here too so the function doesn't continue to run

2022-12-28 01:49 UTC, harryttd commented on utils/snapshot-downloader.sh
> +  fi
does the snapshot file also needs to be deleted?

2022-12-28 01:49 UTC, harryttd commented on utils/snapshot-downloader.sh
> +      echo "Error: sha256 checksum of the downloaded file did not match checksum from metadata file." >&2
Is there anything we can do to stop the process from continuously trying to download the same file when the hash doesn't match?

2022-12-28 01:49 UTC, harryttd commented on utils/config-generator.py
> +        matching_snapshots = sorted(matching_snapshots, key=lambda d: d["block_height"])
I think all of the prop lookups need `.get()`, not just block_height. If the aritifact json file is missing any field it will cause the script to crash.

2022-12-28 01:56 UTC, nicolasochem commented on utils/snapshot-downloader.sh
> +  fi
no, it will be overwritten later

2022-12-28 01:57 UTC, nicolasochem commented on utils/snapshot-downloader.sh
> +      touch ${data_dir}/disk_space_failed
right. it was the case, but I removed it during previous review round. re-added

2022-12-28 01:57 UTC, harryttd commented on utils/config-generator.py
> +    full_snapshot_url = os.environ["FULL_SNAPSHOT_URL"]
I think this still needs one more thing: `prefer_tarballs = os.environ.get("PREFER_TARBALLS", "").lower() in ("true", "1", "t")
It needs to default to "", otherwise it will try .lower() on None type

2022-12-28 01:59 UTC, nicolasochem commented on utils/snapshot-downloader.sh
> +      touch ${data_dir}/sha256sum_failed
not needed, that's the end of the function

2022-12-28 02:00 UTC, harryttd commented on utils/snapshot-downloader.sh
> +  fi
why not delete it though? Allow the current process to clean up after itself and not leave anything hanging from it?

2022-12-28 02:03 UTC, nicolasochem commented on utils/snapshot-downloader.sh
> +  fi
done

2022-12-28 02:03 UTC, nicolasochem commented
> Is there anything we can do to stop the process from continuously trying to download the same file when the hash doesn't match?

no, but you could argue it's the fault of the snapshot website so it's fine.

2022-12-28 02:05 UTC, harryttd commented on utils/config-generator.py
> +            s for s in matching_snapshots if octez_version in s.get("tezos_version")
If tezos_version doesn't exist it will be trying to look up a str in Nonetype
```suggestion
            s for s in matching_snapshots if octez_version in s.get("tezos_version", "")
```

2022-12-28 02:09 UTC, harryttd commented on utils/snapshot-downloader.sh
> +      touch ${data_dir}/disk_space_failed
should we log the size of the file for visibility so they can easily tell how much more space is required? I don't think they'll know easily offhand bec config gen does a lot of sorting to pick the correct config. So it isn't easy to determine the size of the file chosen to download.

2022-12-28 02:12 UTC, harryttd commented on utils/snapshot-downloader.sh
> +      touch ${data_dir}/sha256sum_failed
true although if we continue to add to add logic to this function we may not realize that we didn't return from that logic block.

2022-12-28 02:12 UTC, nicolasochem commented on utils/snapshot-downloader.sh
> +      touch ${data_dir}/disk_space_failed
done

2022-12-28 02:13 UTC, nicolasochem commented on utils/snapshot-downloader.sh
> +      touch ${data_dir}/sha256sum_failed
done

2022-12-28 02:25 UTC, nicolasochem commented
I retested all scenarios listed in PR description with [0a98d1b](https://github.com/oxheadalpha/tezos-k8s/pull/525/commits/0a98d1bd970e38a98ebd653f934198bc8e3d7097), it still works. Please re-review @harryttd

2022-12-28 02:30 UTC, harryttd commented on utils/config-generator.py
> +            print(node_snapshot_config_json, file=json_file)
Perhaps we shouldn't even be creating this file if the snap config function returns None. Then `if [ "$(cat ${data_dir}/snapshot_config.json)" == "null" ];` in the downloader needs to check if the file exists. Instead of assuming it always exists with the possibility of the file being created without containing any data.

2022-12-28 02:41 UTC, harryttd approved these changes
I haven't tested only reviewed the code but i'm assuming it all works now.

2022-12-28 02:52 UTC, nicolasochem commented
Yes, I just retested everything on the very latest commit, it's fine. I also tried spinning up a rolling node while only setting the archive tarball url, to verify that the file is not being created.

2022-12-28 02:52 UTC, merged