tezos-proto-cruncher chart
oxheadalpha/tezos-k8s pull request #532
Opened 2023-01-18 06:08 UTC by nicolasochem

This chart deploys a daemonset in your cluster. the daemonset runs a parallel search for a vanity protocol hash.

It takes s3 bucket credentials. Protocol is downloaded from bucket then results are written to the bucket.

It does not terminate: it keeps running until the cluster is torn down.

2023-01-24 22:40 UTC, harryttd requested changes

2023-01-24 22:40 UTC, harryttd commented on charts/tezos-proto-cruncher/values.yaml
> +vanity_string: "PtMumbai"
sorry... do you mind making these camel case to keep in line with the k8s convention of naming properties? The medium article would have to be updated too.

2023-01-24 22:40 UTC, harryttd commented on charts/tezos-proto-cruncher/templates/config.yaml
> +  BUCKET_REGION: "{{ .Values.bucket_region}}"
maybe some of these should be secrets as well? I would think at least the access key id would be preferably a secret. But whatever you think.

2023-01-24 22:40 UTC, harryttd commented on charts/tezos-proto-cruncher/scripts/proto-downloader.py
> +PROTO_NAME = os.getenv("PROTO_NAME")
Maybe fail fast via another getter if the env vars don't exist? Say endpoint doesn't exist. The url will be created with `None`. Might as well fail fast and the stack trace will clearly show why.

2023-01-24 22:40 UTC, harryttd commented on charts/tezos-proto-cruncher/scripts/tezos-proto-cruncher.sh
> +num_cores=$(grep -c ^processor /proc/cpuinfo)
perhaps should be configurable how many cores to run on? If the user only has minimal nodes and or node resources, this could really slow down their other workloads.

2023-01-24 22:40 UTC, harryttd commented on charts/tezos-proto-cruncher/scripts/proto-cruncher.py
> +    new_nonce_digits = ''.join(random.choice(string.digits) for _ in range(16))
how is the user supposed to change this? Shouldn't it be configurable via values.y?

2023-01-24 22:40 UTC, harryttd commented on charts/tezos-proto-cruncher/scripts/proto-cruncher.py
> +            s3.Object(BUCKET_NAME, f"{PROTO_NAME}_{new_hash}").put(Body=new_nonce)
error handle? If this returns an error the script would exit it seems. Even though k8s should restart the container, depending upon the error type, perhaps the `while True` should continue running as the error may only be temporary. Like a network error or something.

2023-01-24 22:40 UTC, harryttd commented on charts/tezos-proto-cruncher/scripts/proto-cruncher.py
> +BUCKET_REGION = os.getenv("BUCKET_REGION")
fail fast if vars not set?

2023-01-24 22:40 UTC, harryttd commented on charts/tezos-proto-cruncher/scripts/proto-cruncher.py
> +        if BUCKET_NAME:
Isn't the goal of the chart to upload hashes? So if no bucket name exists this script will loop endlessly and not store the results anywhere. Shouldn't it error? Or at least at the top of the file error if the env var isnt set.

2023-01-24 22:43 UTC, harryttd commented
Suggestion: explain how to uninstall the chart in the medium article when it isn't needed anymore

2023-01-24 23:54 UTC, nicolasochem commented on charts/tezos-proto-cruncher/scripts/proto-cruncher.py
> +BUCKET_REGION = os.getenv("BUCKET_REGION")
as per the medium article, users are free to download and run this script on their computer as well. So I'm not going to fail if the s3 variables are not set. For the `VANITY_STRING`, sure.

2023-01-24 23:58 UTC, harryttd commented on charts/tezos-proto-cruncher/scripts/proto-cruncher.py
> +BUCKET_REGION = os.getenv("BUCKET_REGION")
ah, i see. very good

2023-01-24 23:59 UTC, harryttd commented on charts/tezos-proto-cruncher/scripts/proto-cruncher.py
> +    new_nonce_digits = ''.join(random.choice(string.digits) for _ in range(16))
since i forgot about running this script locally, i guess it could be an env var

2023-01-25 03:31 UTC, nicolasochem commented on charts/tezos-proto-cruncher/scripts/proto-cruncher.py
> +        if BUCKET_NAME:
if no bucket name exists, I assume this is a local run and printing the nonces out in the console will be sufficient.

2023-01-25 04:25 UTC, nicolasochem commented on charts/tezos-proto-cruncher/templates/config.yaml
> +  BUCKET_REGION: "{{ .Values.bucket_region}}"
I think only stuff explicitly designated as secret should be a k8s secret.

2023-01-25 20:10 UTC, harryttd commented on charts/tezos-proto-cruncher/scripts/proto-cruncher.py
> +                continue
Thanks for adding this. The thing is that if there is a type of error that will never resolve itself, hashes will continue to be generated pointlessly, using a lot of resources. I assume there is a way to differentiate between diff errors and  raise an exception if there is an unresolvable error.

2023-01-25 22:36 UTC, nicolasochem commented on charts/tezos-proto-cruncher/scripts/proto-cruncher.py
> +                continue
Not really. If hashes can't upload, it's still good to generate them. You can look at the logs of your pod and retrieve them.

2023-01-26 23:13 UTC, harryttd approved these changes

2023-01-26 23:23 UTC, merged