Add support external db support for tzkt
oxheadalpha/tezos-k8s pull request #559
Opened 2023-03-08 17:35 UTC by puppetninja

This PR allows external postgres db to specified as backend db for tzkt

2023-03-08 21:35 UTC, harryttd commented
Thanks for the contribution! I'll be leaving some comments

2023-03-09 21:21 UTC, harryttd commented on charts/tezos/templates/tzkt_indexer.yaml
> +      {{- if $tzkt_indexer.db.snapshot_url }}
Why if we are using a separate db from the pod should we not handle snapshots anymore? Even if say there is a separate postgres db within the cluster, or an RDS instance, we should still be able to download snapshots for quick db restore.

2023-03-09 21:31 UTC, puppetninja commented on charts/tezos/values.yaml
> +#       ## from a snapshot
I wrote this down based on the doc here
https://github.com/baking-bad/tzkt

> No archive node needed. There is no need to use an archive node (running in "archive" mode). If you bootstrap the indexer from the most recent snapshot, using a simple rolling node will be enough.

I think archive node is only needed if you start from scratch for indexing, but if you import a db snapshot or dumped backup, you can use a rolling node to catch up to latest block for indexing

2023-03-09 21:37 UTC, harryttd requested changes

2023-03-09 21:37 UTC, harryttd commented on charts/tezos/templates/tzkt_indexer.yaml
> +    {{- if not $tzkt_indexer.db.isExternal }}
Why if we are using a separate db from the pod should we not handle snapshots anymore? Even if say there is a separate postgres db within the cluster, or an RDS instance, we should still be able to download snapshots for quick db restore.

2023-03-09 21:37 UTC, harryttd commented on charts/tezos/templates/tzkt_indexer.yaml
> +          image: "{{ $tzkt_indexer.images.postgres }}"
I just want to leave a comment here explaining my understanding of how this will work with the latest versions of tzkt. We are doing a big jump from the old v1.6 tzkt version we handled, to the latest v11 version. 

They have now implemented a way for some version upgrades to not require dropping the db and syncing from scratch or using a snapshot. Just by changing the docker image it can perform necessary db migrations. This container will always drop and re-create the db when there is a new snapshot url. That should still be the correct functionality. Because if a new url is being used that implies that the user needs a fresh db to import the snapshot into.

If the user just updates the docker images, that implies that there is no need to recreate the db. Rather the migrations would run and update automatically.

2023-03-09 21:39 UTC, harryttd commented on charts/tezos/values.yaml
> +#       ## from a snapshot
oh very cool. Can you add to the comment that a rolling node is sufficient instead of an archive node?

2023-03-09 21:48 UTC, puppetninja commented on charts/tezos/values.yaml
> +#       ## from a snapshot
yes, will do

2023-03-14 17:28 UTC, puppetninja commented on charts/tezos/templates/tzkt_indexer.yaml
> +    {{- if not $tzkt_indexer.db.isExternal }}
I am a a little bit lost here, basically if there is an external db instance, we manage the snapshot download and import independently from this chart ?

2023-03-14 17:36 UTC, puppetninja commented on charts/tezos/templates/tzkt_indexer.yaml
> +          image: "{{ $tzkt_indexer.images.postgres }}"
I am not sure whether I follow here as I didn't change any db migration logic, and I tested with db in same pod as well, the only pain for me is the mainnet db import within the same pod takes ages for the pod to be up. So I decided to use chart from bitnami which allows me to customized and import the db snapshot.

2023-03-14 17:40 UTC, puppetninja commented on charts/tezos/templates/tzkt_indexer.yaml
> +        {{- if not $tzkt_indexer.db.isExternal }}
> However, i left another comment saying that we should still provide the upgrade functionality for external db's if a snapshot url is provided.

Sorry I am not sure I follow here, may I ask why ? I would assume this will be handled by DBA or DB chart independently ?

2023-03-14 17:44 UTC, puppetninja commented on charts/tezos/values.yaml
> +#       ## from a snapshot
Done

2023-03-15 16:19 UTC, harryttd commented on charts/tezos/templates/tzkt_indexer.yaml
> +        {{- if not $tzkt_indexer.db.isExternal }}
I hear your point. We could continue to leave it up to the chart to handle snapshots and not need that a human needs to manually handle them. The code already exists. @nicolasochem What do you think?

2023-03-15 16:31 UTC, harryttd commented on charts/tezos/values.yaml
> +#       rpc_url: http://rolling-node-0.rolling-node:8732
please clean up. things are repeated and the tzkt github link is used above

```suggestion
#       ## RPC url of the node to index. A rolling node is sufficient if the
#       ## indexer is bootstrapped from the most recent snapshot. Otherwise an
#       ## archive node is needed.
#       rpc_url: http://rolling-node-0.rolling-node:8732
```

2023-03-15 16:59 UTC, nicolasochem commented on charts/tezos/templates/tzkt_indexer.yaml
> +        {{- if not $tzkt_indexer.db.isExternal }}
The right time to import a snapshot is when the DB starts. If the DB is managed by another chart, then this other chart is responsible for downloading the snapshot. Having logic in our chart to download snapshot only makes sense when the chart also handles the DB. Otherwise, without control of the DB itself, it's impossible to decide when/whether to import or not.

DB management is something that we provide for prototyping and demos, I would expect prod deployments to use an externally provisioned DB.

So it makes sense to not import anything is the db is external.

2023-03-16 20:44 UTC, harryttd commented on charts/tezos/templates/tzkt_indexer.yaml
> +        {{- if not $tzkt_indexer.db.isExternal }}
ok makes sense. Thank you. @puppetninja can you please also make sure that `volumeClaimTemplates` are only rendered if we are not using an external db?

2023-03-16 20:47 UTC, harryttd commented on charts/tezos/values.yaml
> +#       indexer: "bakingbad/tzkt-sync:1.11.1"
they just came out with v12 https://github.com/baking-bad/tzkt/releases/tag/v1.12.0

2023-03-29 16:27 UTC, puppetninja commented on charts/tezos/templates/tzkt_indexer.yaml
> +          image: "{{ $tzkt_indexer.images.postgres }}"
I just used the bitnami chart to allow me to deploy postgres in a more sophisticated way like multiple replicas and utilized the init  script to import the snapshot just for once

2023-03-29 19:53 UTC, puppetninja commented on charts/tezos/templates/tzkt_indexer.yaml
> +        {{- if not $tzkt_indexer.db.isExternal }}
HI @harryttd 
This is what I see 
![Screenshot from 2023-03-29 21-51-53](https://user-images.githubusercontent.com/2862053/228652123-31028eec-717e-4515-b828-effbd19a5cc4.png)
![Screenshot from 2023-03-29 21-53-22](https://user-images.githubusercontent.com/2862053/228652342-27db41f2-cb0e-4ba2-9853-4a75066119cb.png)

2023-03-29 19:59 UTC, puppetninja commented on charts/tezos/templates/tzkt_indexer.yaml
> +        {{- if not $tzkt_indexer.db.isExternal }}
@harryttd done, can you please review again ?

2023-03-29 20:00 UTC, puppetninja commented on charts/tezos/templates/tzkt_indexer.yaml
> +{{ print " " "server=$(POSTGRES_HOST);port=5432;database=$(POSTGRES_DB);username=$(POSTGRES_USER);password=$(POSTGRES_PASSWORD);command timeout=600;" }}
This is needed  per
https://github.com/baking-bad/tzkt/blob/master/docker-compose.yml#L24

2023-03-29 20:43 UTC, harryttd commented on charts/tezos/templates/tzkt_indexer.yaml
> +{{ print " " "server=$(POSTGRES_HOST);port=5432;database=$(POSTGRES_DB);username=$(POSTGRES_USER);password=$(POSTGRES_PASSWORD);command timeout=600;" }}
I don't think we should be doing this. If something is broken the connection will still wait 10 minutes. The docker compose file defaults to 600s but still lets a user configure the value.

2023-03-29 21:18 UTC, puppetninja commented on charts/tezos/templates/tzkt_indexer.yaml
> +{{ print " " "server=$(POSTGRES_HOST);port=5432;database=$(POSTGRES_DB);username=$(POSTGRES_USER);password=$(POSTGRES_PASSWORD);command timeout=600;" }}
For mainnet we did hit the issue you can find more here
https://github.com/baking-bad/tzkt/issues/146

2023-03-29 21:19 UTC, puppetninja commented on charts/tezos/values.yaml
> +#       rpc_url: http://rolling-node-0.rolling-node:8732
Done

2023-03-29 21:20 UTC, puppetninja commented on charts/tezos/values.yaml
> +#       rpc_url: http://rolling-node-0.rolling-node:8732
And will not do force pushes

2023-03-29 21:22 UTC, harryttd commented on charts/tezos/templates/tzkt_indexer.yaml
> +{{ print " " "server=$(POSTGRES_HOST);port=5432;database=$(POSTGRES_DB);username=$(POSTGRES_USER);password=$(POSTGRES_PASSWORD);command timeout=600;" }}
ok very cool. Let's make it configurable though?

2023-03-29 21:23 UTC, puppetninja commented on charts/tezos/templates/tzkt_indexer.yaml
> +{{ print " " "server=$(POSTGRES_HOST);port=5432;database=$(POSTGRES_DB);username=$(POSTGRES_USER);password=$(POSTGRES_PASSWORD);command timeout=600;" }}
Okay, I can check into this

2023-03-29 21:24 UTC, puppetninja commented on charts/tezos/templates/tzkt_indexer.yaml
> +{{ print " " "server=$(POSTGRES_HOST);port=5432;database=$(POSTGRES_DB);username=$(POSTGRES_USER);password=$(POSTGRES_PASSWORD);command timeout=600;" }}
I was not sure whether I should create a dedicated configmap for this, as this is not really go into db creds secret imo

2023-03-29 21:26 UTC, puppetninja commented on charts/tezos/templates/tzkt_indexer.yaml
> +{{ print " " "server=$(POSTGRES_HOST);port=5432;database=$(POSTGRES_DB);username=$(POSTGRES_USER);password=$(POSTGRES_PASSWORD);command timeout=600;" }}
same for db port maybe

2023-03-30 13:42 UTC, puppetninja commented on charts/tezos/templates/tzkt_indexer.yaml
> +{{ print " " "server=$(POSTGRES_HOST);port=5432;database=$(POSTGRES_DB);username=$(POSTGRES_USER);password=$(POSTGRES_PASSWORD);command timeout=600;" }}
@harryttd done and I verified on our testing cluster

2023-03-30 17:31 UTC, puppetninja commented on charts/tezos/templates/tzkt_indexer.yaml
> +      {{- if $tzkt_indexer.db.snapshot_url }}
@harryttd done

2023-03-30 21:09 UTC, harryttd approved these changes
thank you!

2023-03-30 21:09 UTC, merged