Add ability to set operations-pool per baker
oxheadalpha/tezos-k8s pull request #577
Opened 2023-04-11 21:01 UTC by nicolasochem

Operations-pool allows the baker to target a flashbake endpoint or other external mempool provider by passing a URL. This was previously done by passing BAKER_EXTRA_ARGS env variable, but it would be the same for every baker in your pod. This allows setting an endpoint per baking address.

2023-04-11 23:00 UTC, harryttd requested changes

2023-04-12 05:24 UTC, nicolasochem commented on charts/tezos/templates/configs.yaml
>    namespace: {{ .Release.Namespace }}
Good point, previously the `baker-config` cm would always exist. I have now re-added a condition, but it checks for the presence of bakers rather than a specific toggle vote. Whenever there is a baker, it's mandatory to set the toggle vote in values.yaml so it's ok now.

I tested in minikube on a private chain and the cm existed. Then I tried a public chain (mumbainet) and it didn't.

2023-04-14 05:03 UTC, harryttd commented on charts/tezos/templates/nodes.yaml
> -{{- end }}
I beleive this still needs a check. If a baker is not running then the cm doesn't exist

2023-05-17 04:53 UTC, nicolasochem commented on charts/tezos/templates/nodes.yaml
> -{{- end }}
now fixed

2023-05-17 16:11 UTC, harryttd commented on charts/tezos/values.yaml
>  #       vote:
I just realized, is this example inaccurate? It's an account for a baker, but the key passed is a public key and is_bootstrap_baker_account is false. To bake it needs a secret key unless passed a `signer_url` or `key_id`. Then public key is fine. But we show those examples later.

Perhaps baker0 should be what baker1 is but named `node0` or the like, and is shouldn't have `operations_pool` and `protocols`, because in this example baker1 isn't actually baking.

2023-05-17 16:16 UTC, nicolasochem commented on charts/tezos/values.yaml
>  #       vote:
In case of public chains, we don't actually need `is_bootstrap_baker_account` and `bootstrap_balance`. This is only relevant for private chains, as explained a bit above in the same file.

I fixed it in a different way, by making sure baker1 has a secret key and removing the fields specific to private chain.

2023-05-18 17:47 UTC, harryttd commented on test/charts/private-chain.expect.yaml
> +        - name: baker-config
This sts isn't baking so I don't believe the baker config should be here

2023-06-02 21:33 UTC, nicolasochem commented on test/charts/private-chain.expect.yaml
> +        - name: baker-config
fixed

2023-06-02 21:54 UTC, harryttd approved these changes
looks good

2023-06-02 21:56 UTC, merged