Add timeout for /is_synced endpoint in sidecar.py
oxheadalpha/tezos-k8s pull request #581
Opened 2023-04-27 14:09 UTC by puppetninja

In out prod environment we could observe that requests piling up as there is no timeout in default requests get method. Here we timeout and close the connection timely to avoid the piling up.

This is an alternative way to fix the issue mentioned here https://github.com/oxheadalpha/tezos-k8s/pull/562

2023-05-01 17:10 UTC, nicolasochem approved these changes
thanks, it looks like a better way to implement sidecar, as it does not leave any state behind.

2023-05-01 17:48 UTC, harryttd commented on utils/sidecar.py
> +# Default readiness probeperid timeout is 1s, timeout sync request before that and return a
what is probeperid?

2023-05-01 20:16 UTC, puppetninja commented on utils/sidecar.py
> +# Default readiness probeperid timeout is 1s, timeout sync request before that and return a
it is a typo...
https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
periodSeconds: How often (in seconds) to perform the probe. Default to 10 seconds. Minimum value is 1.

2023-05-02 21:55 UTC, harryttd commented on utils/sidecar.py
> +# Default readiness probeperid timeout is 1s, timeout sync request before that and return a
the docs you reference say default is 10s but your comment says 1s

2023-05-02 22:00 UTC, harryttd requested changes
please see my latest comment

2023-05-03 13:44 UTC, puppetninja commented
> please see my latest comment
I have  updated the comment with right probe filed name, please have a review

2023-05-03 17:03 UTC, merged