Add Node RPC and BCD ingresses
oxheadalpha/tezos-k8s pull request #583
Opened 2023-05-04 22:20 UTC by harryttd

2023-05-04 23:45 UTC, harryttd commented on charts/tezos/values.yaml
> +  apiUrl: "" # http://localhost:14000
I hope this is clear. Instead of needing to repeat the url and hostname for the ingress section and gui section, we define it just once and Helm does lookups for both gui and ing.

2023-05-04 23:47 UTC, nicolasochem requested changes

2023-05-04 23:47 UTC, nicolasochem commented on charts/tezos/values.yaml
> +  apiUrl: "" # http://localhost:14000
It says "stripped of http(s)" but the example has a "http://"

2023-05-04 23:48 UTC, harryttd commented on charts/tezos/values.yaml
> +  apiUrl: "" # http://localhost:14000
yes, but is also refers to when users provide their own https urls

2023-05-04 23:50 UTC, nicolasochem approved these changes
Looks good, I didn't try but I am told by the author that it's already deployed in a private deployment and works fine.

2023-05-04 23:50 UTC, merged

2023-05-11 12:38 UTC, gisele-igore commented on charts/tezos/values.yaml
> +  apiUrl: "" # http://localhost:14000
Nice one