Add local_storage_size option in values
oxheadalpha/tezos-k8s pull request #594
Opened 2023-07-11 09:29 UTC by puppetninja

Some cloud provider have minimum pvc size requirement, like Aliyun, this option would also tezos-k8s to be deployed under such scenarios.

2023-07-11 17:48 UTC, harryttd requested changes

2023-07-11 17:48 UTC, harryttd commented on charts/tezos/templates/nodes.yaml
>  {{- end }}
I don't think we need to introduce a brand new field here. You can use logic to determine the default size and just use `storage_size`.

2023-07-11 19:34 UTC, puppetninja commented on charts/tezos/templates/nodes.yaml
>  {{- end }}
I think it would be confusing, to configure pvcs for different purposes with same helm value, they even have different pvc names.

2023-07-11 19:55 UTC, harryttd commented on charts/tezos/templates/nodes.yaml
>  {{- end }}
i see what you are saying. Maybe we rename local_storage_size then because that sounds like the size of the local temp memory of the machine which isn't persistent and isn't what is being configured. Maybe `local_storage_pv_size`?

2023-07-11 21:09 UTC, harryttd approved these changes
Thank you!

2023-07-12 19:25 UTC, merged

2023-07-12 19:27 UTC, puppetninja commented
I rebased it instead of squashing my commits, sorry for that