Signer authorized keys
oxheadalpha/tezos-k8s pull request #610
Opened 2023-10-23 20:05 UTC by nicolasochem

2023-10-25 03:06 UTC, harryttd requested changes

2023-10-25 03:06 UTC, harryttd commented on utils/config-generator.py
> +    if MY_POD_TYPE == "signing" and len(authorized_keys) > 0:
could be simplified to 
```suggestion
    if MY_POD_TYPE == "signing" and len(authorized_keys):
```

2023-10-25 04:12 UTC, nicolasochem commented on mkchain/tqchain/mkchain.py
> +        for account in [*baking_accounts, *["authorized-key-0"]]:
no, because mkchain currently generates only one signer for all the bakers... if there was one key per baker, every baker could sign with each other's auth key, which is not realistic...

2023-10-25 04:14 UTC, nicolasochem commented on utils/config-generator.py
> +    if MY_POD_TYPE == "signing" and len(authorized_keys) > 0:
your suggestion is harder to read IMO

2023-10-25 04:25 UTC, nicolasochem commented on charts/tezos/scripts/remote-signer.sh
> -CMD="$TEZ_BIN/octez-signer -d $CLIENT_DIR launch http signer --magic-bytes 0x11,0x12,0x13 --check-high-watermark -a 0.0.0.0 -p 6732"
I am not too sure. I want sane defaults for both private chain and public baker. A public baker will by default not use remote signer, then it can sign everything anyway.

It has happened to me in the past that I launch a private chain with just one baker, shell into the node and try to do transfers from the only account that exists - the baker account - but the signer won't let me. It's annoying.

I am not sure whether I would recommend mainnet baking with a hot key anyway. The guides we have posted make clear we prefer people to use KMS.

2023-10-25 04:29 UTC, nicolasochem commented on utils/config-generator.py
> +            return True
reformatting done. Yes, the activation itself is the edge case. I rephrased.

2023-10-25 17:53 UTC, nicolasochem commented
I have tested this end-to-end with the lambda on ghostnet so marking this ready:

https://ghost.tzstats.com/tz1Qf1pSbJzMN4VtGFfVJRgbXhBksRv36TxW#baking

2023-10-27 15:32 UTC, harryttd requested changes

2023-10-27 15:32 UTC, harryttd commented on charts/tezos/scripts/remote-signer.sh
> -CMD="$TEZ_BIN/octez-signer -d $CLIENT_DIR launch http signer --magic-bytes 0x11,0x12,0x13 --check-high-watermark -a 0.0.0.0 -p 6732"
perhaps in the future we'll have a config that let's users specify which operations to allow/disallow

2023-10-27 15:32 UTC, harryttd commented on charts/tezos/values.yaml
> +#                         will be used to sign every signature request.
It's not clear except for the signer comment doc later on that this is a list of account names. Not actual keys. The comment indicates that keys are what should be used.

2023-10-27 15:32 UTC, harryttd commented on charts/tezos/values.yaml
> +#     - authorized-key-0
Comment implies keys should be used while the example show's an account name.

2023-10-27 15:33 UTC, harryttd commented
Perhaps Helm should do validation on the auth accounts. It could fail fast if for example, a signer/baker specifies an account that doesn't exist.

2023-10-27 15:45 UTC, harryttd commented
My thinking is if an auth key is not defined, and generate unsafe data is true, that they can be auto generated similar to baking accounts. https://github.com/oxheadalpha/tezos-k8s/blob/cc7781527a207f6e9b3d8b1fdc30518b55e914bc/utils/config-generator.py#L221

2023-11-06 05:19 UTC, nicolasochem commented on charts/tezos/values.yaml
> +#     - authorized-key-0
fixed

2023-11-06 05:19 UTC, nicolasochem commented on charts/tezos/values.yaml
> +#                         will be used to sign every signature request.
fixed

2023-11-06 05:21 UTC, nicolasochem commented
> Perhaps Helm should do validation on the auth accounts. It could fail fast if for example, a signer/baker specifies an account that doesn't exist.

Done.

> My thinking is if an auth key is not defined, and generate unsafe data is true, that they can be auto generated similar to baking accounts.

Can I skip? I actually want to deprecate account autogeneration. I think generation of accounts should happen when you create the yaml file (with mkchain or otherwise).

2023-11-06 15:08 UTC, harryttd commented on charts/tezos/templates/_helpers.tpl
> +    {{- if not (index $.Values.accounts $key) }}
This is great. I would also make sure that an actual key is provided on the account definition. 
```suggestion
    {{- if not (index $.Values.accounts $key "key") }}
```

2023-11-06 15:31 UTC, nicolasochem commented on utils/config-generator.py
> +            # regardless of which baker does it.
Yes, right, it probably does not have to be a baker, since at block 0, the list of bakers is not known... But what's the alternative? create a dedicated list of authorized_keys for activation? I've never activated a chain with an account that's not a baker, so I think it's fine.

2023-11-06 20:39 UTC, harryttd commented on utils/config-generator.py
> +            # regardless of which baker does it.
yeah i think it's fine as is. 

What could be done is look up the signer that is signing for the baker baking with the activation key, get this signer's auth keys, and then only import those keys. If no signer is found, then no auth key would be required for activation.

2023-11-06 20:45 UTC, harryttd approved these changes

2023-11-06 20:48 UTC, merged